### ISSUE TITLE
Wow W3TC on WP has been updated to 0.9.5!

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#112]
[And look at that change log](https://wordpress.org/plugins/w3-total-cache/changelog/) ...Lots of fixes

**Comment by charlesLF** [comment]
Many of them taken from right here :)

**Comment by nigrosimone** [comment]
Wow! Ok.. Many of them taken from right here... but many other are totally new...

**Comment by nigrosimone** [comment]
Mhh same version of fix-w3tc 0.9.0.5...

**Comment by vijayaraghavanramanan** [comment]
I hope he puts it on Github. The WPTavern article from a few months ago quoted him saying this. 

Github is so much better than Wordpress forums for discussions. 

#FrederickOrBust

**Comment by vijayaraghavanramanan** [comment]
I have an idea: 

You contributors to fix-w3tc can offer a companion plugin. I think the new version at WP still has the AMP error and sitemap priority error. 

In addition, the new version of W3TC offers progressively loading CSS as a paid option. 

You could make a companion plugin which creates more tabs in the original plugin and have this (such as a box for critical css, unchecking W3TC css optimization) and bugfixes and other things such as pushing assets (HTTP2 server side push).

**Comment by andreasnrb** [comment]
@vijayaraghavanramanan I wonder if will actually put it on GitHub. Also there is quite a lot of things going on in the new plugin that will cause issues for some. Such as the unannounced requirement of >=PHP 5.3.
Don't know what the minium PHP version is currently.

**Comment by nigrosimone** [comment]
I don't understand Frederick, he disappears for a year and come back with a huge update, with so many new feature, so many bug fix an so many new and old bugs.

Why?

He could come back with a little update for fix some old bugs like the php7 compatibility and the latest security issue and all the people would be happy. 

The old version works most of the time, this version has so many fatal issue.

**Comment by charlesLF** [comment]
I think he may have felt pressured to release the new version, given the newly discovered XSS vulnerability, so he pushed v0.9.5 without extensive testing ... but that's just my theory.

I already started fixing some of the bugs mentioned in the wordpress forums, in case Frederick decides to disappear again.
My branch can be found here: https://github.com/charlesLF/fix-w3tc/tree/w3tc-0-9-5

Moving on, wha about if we push the changes we have made in fix-w3tc as a new plugin in the WP repo. That way people who don't feel comfortable with the re-structured W3TC version could still its power with the 0.9.4-fix version for backward compatibility.

This is similar to what happened with the [NextGen/NextCellent plugin](http://wpgetready.com/nextcellent-gallery/)

**Comment by nigrosimone** [comment]
> I already started fixing some of the bugs mentioned in the wordpress forums, in case Frederick decides to disappear again.

ehehhehe :D

> Moving on, wha about if we push the changes we have made in fix-w3tc as a new plugin in the WP repo. 

eh... a this point it's not bad idea.

**Comment by vijayaraghavanramanan** [comment]
Yeah I too think the vulnerability forced him to release. WP Tavern and Yoast's blog didn't sound good. 

But Frederick is a great great guy. I am sure he has some important things due to which he couldn't keep his promises. 

Also no other plugin comes even close. I mean I try them sometime but quickly uninstall soon. So W3TC is so good. 

This fix-w3tc at Wordpress looks like a good idea.

**Comment by nigrosimone** [comment]
> But Frederick is a great great guy. I am sure he has some important things due to which he couldn't keep his promises.

yes I agree. however, it should improve communication with the community. Also at this time, he did not say anything: no tweet, no post, nothing! why?

**Comment by charlesLF** [comment]
`But Frederick is a great great guy. I am sure he has some important things due to which he couldn't keep his promises. `

I agree, and I admire the work done in W3TC. It is by far my favorite caching/optimization plugin and has done wonders on the many websites that I use it on, and the coding approach used in the plugin (whether in v0.9.4 or v0.9.5) shows great skill.
That was actually the main reason I got excited about contributing here. It felt as if I'm giving back to a plugin that has given me a lot for free!

I also understand the pressure of having a plugin used by 1+ million website, and having to keep up with all the problems that could arise from the different configurations.

My issue is with the lack of communication, as @nigrosimone pointed out. It is clear that there are a lot of people in the community that are ready to give back to W3TC, and for free. This repository is the biggest proof.

I don't appreciate all the reports on the WP support forum of people purchasing Premium support and never receiving any replies. Heck, the new version even increased the price for premium support https://plugins.trac.wordpress.org/changeset/1502418

Instead of keeping everyone in the dark, I would recommend that Frederick harnesses the power of open source by putting the plugin on github, and allowing for different people to contribute to the fixes and code quality of the project.

**Comment by lukecav** [comment]
The other issue, ends up being if a user uses the GitHub Updater plugin to install the forked version of W3TC. But on the updates screen in WP it will show that the current update is 0.9.5. So if a user does update from the forked version to the repo current version, it will be confusing for the user, which version they are using.

**Comment by charlesLF** [comment]
@lukecav .. IF the fix-w3tc is to be released as a separate plugin, it should be released under a new name to clearly distinguish it from the official plugin.

It should also gracefully deactivate in case the official w3tc plugin is active and give the admin a notification saying that the community edition can not run side-by-side with the official edition.

**Comment by Volnus** [comment]
I believe the best way is to see if the GitHub can be opened and we can work with Townes on it because creating a W3TC fix plugin won't help the million active users of that plugin only the few that switch.

**Comment by andreasnrb** [comment]
I used to know the plugin like the back of my hand, at least pre 0.9.5. Even thought about making a proper fork. Talked with Simone about contributing here and I just might. But I wouldn't just want to fix issues with current release, but make it more structurally sound.

**Comment by vijayaraghavanramanan** [comment]
The best scenario is like wp-minify-fix which is a fix of wp-minify. Someone named NodeCode fixed the original plugin and even got the original author to be a co-author of wp-minify-fix!

**Comment by vijayaraghavanramanan** [comment]
> The other issue, ends up being if a user uses the GitHub Updater plugin to install the forked version of W3TC. But on the updates screen in WP it will show that the current update is 0.9.5. So if a user does update from the forked version to the repo current version, it will be confusing for the user, which version they are using.

Luke has a point. Sometimes servers update Wordpress and/or plugins without asking even if you've set the option to not do so. And since there was a security issue, some hosts might run a patch across all sites to update it. So a solution with versioning is needed for users of this fork.

**Comment by nigrosimone** [comment]
>  it will show that the current update is 0.9.5

this is a strange coincidence... same version of fix-w3tc.

**Comment by Volnus** [comment]
I don't really see the naming of versions to be a strange coincidence. Think the update was planned to be 1.0.0 but because of the security issue he published everything under a point release .9.5 I see nothing weird about that naming convention since it's clear the actual release has done a ton when it comes to feature integration ~

**Comment by nigrosimone** [comment]
new update it is going wrong...
[![comp.jpg](http://s10.postimg.org/3ug0amymx/comp.jpg)](http://postimg.org/image/bzy28smvp/)

**Comment by Tarun80** [comment]
This is one interesting thing that I noticed in the new release:

https://plugins.trac.wordpress.org/changeset/1502418

**Comment by nigrosimone** [comment]
@Tarun80 yep, i too have noticed it. 

> Less than 15 Minute Email Support $175 USD

it seems a little too expensive....

**Comment by Volnus** [comment]
From what i can tell most people who are complaining are those running older versions of php (5.2 in particular)

**Comment by lukecav** [comment]
The minimum version of PHP seems to be 5.3 on W3 Total Cache on the repo now. https://wordpress.org/support/topic/new-w3tc-requires-php-5-3/

**Comment by nigrosimone** [comment]
@lukecav we are at work https://github.com/charlesLF/fix-w3tc/pull/3/commits/a595a46ba6956fe594ba2871a6576da2eb746379

**Comment by lukecav** [comment]
@nigrosimone

Nice.

**Comment by vijayaraghavanramanan** [comment]
Frederick Townes says he might push another release fixing bugs here: 

https://www.w3-edge.com/weblog/2016/09/w3-total-cache-v0-9-5/

WP Tavern also wrote on it: https://wptavern.com/w3-total-cache-0-9-5-packages-xss-vulnerability-patch-with-major-update
