### ISSUE TITLE
Installed this After Bad 0.9.5 Plugin Release -- One Issue

### ISSUE THREAD

**Issue by casbboy** [szepeviktor/fix-w3tc#114]
After having 0.9.5 crash my site, the new update is chock full of bugs, I decided to upload this GitHub fix version instead. 

Everything seems fine, except I keep getting the alert to fix:

Edit file /usr/home/trailera/public_html/nginx.conf and replace all lines between and including # BEGIN W3TC Minify cache and # END W3TC Minify cache markers with:

I did the code exactly as it wanted, restarted nginx, and it still has the error. So not sure if the error just doesn't know to go away on this GitHub version (it doesn't exist on the 0.9.4 base), but want to make sure Minify is cacheing properly. 

I can't just keep deleting and adding the same code, so hoping this is a common issue.

Cheers
Ryan

**Comment by amiga-500** [comment]
Hmmm...never heard/seen that issue before.  Checking the code i notice this message pops up when the plugin fails to get the correct filesystem rights when it tries to manipulate the filesystem...in other words, it is having issues trying to write to nginx.conf because it doesn't have read/write permissions.  I assume your ngix.conf file is **644**?  Can you verify that?

**Comment by casbboy** [comment]
Yes, I do not allow it permission to write to this file, just to prevent it doing something odd and breaking entire server. I manually add it, then restart nginx myself. With the old 0.9.4, the error went away immediately after I updated the nginx.conf file, but it just remains with the GitHub version. So I'm not sure if the Cacheing is working, at least for Minify.

**Comment by amiga-500** [comment]
Ahhh..thats very good to know.  I will do some more hunting to see why it does that.  Thanks for the info!  If i have more questions i'll ask.  Sadly i don't have an nginx server to play with (i usually like to recreate issues on my end prior to fixing them) so this one might take me a tad longer than usual to pinpoint the fix.  Later, if necessary i will reach out to todiaydiyatmo to see about jumping in to assist me since he is the nginx guy among us.  But it shouldn't be necessary.  Anyway, thanks again.

**Comment by casbboy** [comment]
Thanks so much! Yeah, i'm not sure what the deal is. Though it can't write it, it can definitely read it and at least test to make sure config is working. So not sure why it is refusing to see or accept my copy/paste changes.

**Comment by amiga-500** [comment]
Dumb question but i have to ask:  When you manually write the rules into your _nginx.conf_ file then restart nginx, and return to w3tc's screen and have it trigger the error message...are the rules you previously wrote still existing inside your nginx.conf file?  I'm sure they are but again, just have to ask to eliminate that angle.

So far the only way for that error message to repeatedly show is if what was pasted (and saved) contained some unexpected character(s) that wasn't originally there.  For example, saving the output in a different encoding, or adding 1 or more spaces after a rule line before the next line.   w3tc compares the existing rules in the nginx.conf with what it expects to find by first replacing all "\r" and "\n" with just "\n", and removing all spaces at the beginning of each rule line.  And that's it.  So if anything else exists such as extra spaces at the end of each line then it will fail (rules dont exist).

Thanks for info again.

**Comment by casbboy** [comment]
Omg,

I had to do a code compare to spot it. The commented top line for that area of code was one character different, once I fixed it moved forward with the other corrections, and now no error showing at all.

Cheers!
Ryan

**Comment by amiga-500** [comment]
Hey that's AWESOME!  Thanks for the update!
