### ISSUE TITLE
4 new security flaws in the 0.9.4.1

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#117]
Via https://secupress.me/4-new-security-flaws-w3-total-cache-0-9-4-1/

**Comment by charlesLF** [comment]
Let's just remove the support pages from fix-w3tc

**Comment by amiga-500** [comment]
Still working on flaw # 4 before putting up a commit...

### Flaw # 1 
Fixed.  Just a simple "===" is required instead of "==" in _apc.php_ and _apcu.php_
### Flaw 2 & 3:
Fixed.  Because fix-w3tc had already previously removed the support pages visually from the admin screen it makes sense just to  remove the backend support files completely which are:

`inc/options/`**`support.php`**
`lib/W3/AdminActions/`**`SupportActionsAdmin.php`**
`lib/W3/UI/`**`SupportAdminView.php`**
`pub/`**`files.php`**

All 4 of these files arent used by any other function in w3tc beyond the support pages we had removed.  So, great..that worked out!  A small section of related code was also removed from _Menus.php_.
### Flaw 4
Still working on this.  it relates to the import area where users can upload their config file.  The damning issue is that w3tc uses the evil eval() function.  I am not sure how useful this import feature is.  Debating if it should be dropped or if i should just write up a reader that pulls the required config elements from the file and then begins processing each.

Anyway, i just wanted to give an update.

**Comment by charlesLF** [comment]
Only thing I can think of for Flaw 4 is to change the import/export to a json file instead of a raw PHP file

**Comment by amiga-500** [comment]
> Only thing I can think of for Flaw 4 is to change the import/export to a json file instead of a raw PHP file

Ahh right, right..forgot about json.  Thanks for the heads up! :) 
Ok applied new security patch PR #118 and merged

Thanks with the assist, as always!
