### ISSUE TITLE
Emoji and CDN

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [szepeviktor/fix-w3tc#122]
Wordpress enqueues wp-emoji-release.min.js via inline feature detection. 

So suppose my website is on the subdomain www.example.com and the CDN cname is cloud.example.com

The file path in browser should be http://cloud.example.com/wp-includes/js/wp-emoji-release.min.js?ver=4.6.1

But that is not the case. 

It's probably because the URLs are JSONencoded in the inline JS in the HTML.

**Comment by amiga-500** [comment]
Sorry for the delay.  Backlogged.  I'll have to do a test but i notice, at least in "_Auto_" mode, that _wp-emojo-release.min.js_ file is included late (i think it is requested via javascript on the client side).  And so w3tc doesnt know about it at all -- hence, no CDN name used.  I havent checked yet but just going based on memory from way back.  I'll do some digging tonight and update you on a solution.

**Comment by amiga-500** [comment]
Hi @vijayaraghavanramanan 

Ok i did some digging and yea because, as you even noticed, the url is JSON encoded within an inlined JS w3tc has no chance to modify the url to CDN.

However, a solution would be to add the following lines into your theme's _functions.php_ file (don't forget to modify the _**cloud.example.com**_ part:

```php
function my_script_location( $script_url, $script_name ) {
        global $wp_version;
	if ( $script_name == 'concatemoji') {
		$script_url = "http://cloud.example.com/wp-includes/js/wp-emoji-release.min.js?ver=$wp_version";
	}

	return $script_url;
}
add_filter( 'script_loader_src', 'my_script_location', 10, 2 );

```

Cheers
Kimberly

**Comment by vijayaraghavanramanan** [comment]
Hi @amiga-500 

Great. Yeah that code should go in functions.php. 

A more general code would affect w3tc so that it can take care of such issues, not just emoji. 

Which lines did you modify in lib/W3/Plugin/TotalCache.php?

**Comment by amiga-500** [comment]
Ok yea...i will not touch w3tc.  But, since you asked, here were the new lines for _TotalCache.php_:

- First, you'd modify lines **80-85** of _lib/W3/Plugin/TotalCache.php_ from this:
```php
if ($this->can_ob()) {
    ob_start(array(
              &$this,
              'ob_callback'
    ));
}
```
to this:
```php
if ($this->can_ob()) {
    ob_start(array(
              &$this,
              'ob_callback'
    ));
    add_filter( 'script_loader_src', array($this, 'my_script_location'), 10, 2 );
}
```
- And secondly, adding the following function anywhere within _lib/W3/Plugin/TotalCache.php_ (but still inside the _W3_Plugin_TotalCache_ class):
```php
function my_script_location( $script_url, $script_name ) {    
    if ( $script_name == 'concatemoji') {
        if ($this->_config->get_boolean('cdn.enabled')) {
            $w3_plugin_cdn = w3_instance('W3_Plugin_CdnCommon');
            $cdn = $w3_plugin_cdn->get_cdn();
            $script_url = str_replace(w3_get_site_url(), '', $script_url);
            $remote_path = $w3_plugin_cdn->uri_to_cdn_uri($script_url);
            $script_url = $cdn->format_url($remote_path);
        }
    }
    return $script_url;
}
```
