### ISSUE TITLE
[0.9.5] Purge page cache on query string pages not working

### ISSUE THREAD

**Issue by timmen22** [szepeviktor/fix-w3tc#146]
**Issue with 0.9.5**

I enabled the “Cache URIs with query string variables” option to enable page caching on query string pages. The cache method I am using is disk (basic).

Page caching is working properly but when I try to purge the cache (on query string pages) it is not working. Purging the caching on pages without query strings is working fine.

It would be really great if someone can look into this matter

Best regards,

Tim

**Comment by charlesLF** [comment]
Hey @timmen22,

It seems getting this done with W3TC is a bit of a pain.

Instead, I have added a page cache flusher widget in the admin dashboard (Performance => Dashboard).

You can paste any URL you want into the textbox, and it will be purged from the cache.

I have pushed this to my branch in here: https://github.com/charlesLF/fix-w3tc/commits/w3tc-0-9-5

Can you try it out and let me know if this works for you?

**Comment by timmen22** [comment]
Thanks for heling me Charles. It is really much appreciated. After pasting a url the cache is purged so it's working! Is it also possible to make a function that works like this:

When I put the following URL into the textbox:  www.example.com/?utm=* --> purge al pages that start with ?utm

**Comment by charlesLF** [comment]
@timmen22, no problem! Glad to be of help.
I will merge this feature to the 0.9.5 branch on this repo too.

As for the wildcard purging, unfortunately I don't think this is feasible with the W3TC code as it is right now.
I believe this would require adding a separate key somewhere that will track all cached URL's and then use them for purging.
Otherwise, W3TC currently does not "know" which URL's are cached and which ones aren't before they are actually requested, making it unable to interpret wildcards in this context.
