### ISSUE TITLE
[0.9.5] How to set .webp expiration header

### ISSUE THREAD

**Issue by moisb** [szepeviktor/fix-w3tc#157]
Hello. I'm using a plugin to convert the images from my website for .webp format encouraged by Google to be faster. At the same time use the latest official version of W3TC with Amazon Cloudfront "origin push". The .webp images are usually being sent to the Amazon S3 and served by Cloudfront, but Google Pagespeed reclaim "not specified expiration" for all .webp images.
Is a problem of the official version of W3TC? Or missing some setting? Can someone help me?

**Comment by amiga-500** [comment]
Sorry for the delay.  

Because you're using "origin push" you will want to set the expiration header within AWS's S3 Management Console -- i assume Cloudfront returns it back as image/wepb mime type?  Once you do that then you would want to invalidate your .webp images on AWS so they can be relayed to the Cloudfront servers with the new header details.  I prefer "origin pull" over "origin push" because it is much easier to manage.  "origin push" gives you more control though so maybe that is why you are using it.

I havent checked the official version of W3TC yet but by setting the _Performance > Browser Cache > Set Expires Header_ under _Media & Other Files_ it should tell AWS what your image files should be.  Not sure if the official version still has the old bug where it refused to send back the Expire header to AWS.  It's possible because .wepb is not a common standard (yet) that the Expire header is not being associated with it and hence you would prolly have to resort to doing it manually on AWS.

If you did an origin pull you could simply just set within your htaccess: **_ExpiresByType image/wepb A31536000_** where 31536000 is your expire time in seconds

Kimberly

**Comment by amiga-500** [comment]
Not sure if this counts but i've added .webp support into fix-w3tc.

**Comment by ProductivePhysician** [comment]
Hey @amiga-500. 
I just found this version after a google search for cache with webp support.
How is this handled by the plugin? Is it similar to Cache Enabler which creates two cached files, one for webp browsers and one for those that don't support webp?
Cheers!
