### ISSUE TITLE
404 Error on Minimized JS and CSS

### ISSUE THREAD

**Issue by casbboy** [szepeviktor/fix-w3tc#161]
I'm seeing 404 errors on pages.

/wp-content/cache/minify/000000/0ec95/default.include.301799.css
/wp-content/cache/minify/000000/0ec95/default.include-footer.ae7740.js
/wp-content/cache/minify/000000/0ec95/default.include.301799.css
/wp-content/cache/minify/000000/0ec95/default.include-footer.ae7740.js

First, I'm not sure why it is calling each file twice, and why it is calling them at all.

I'm trying to remove these 404 errors. Not sure how.

Cheers
Ryan

**Comment by nigrosimone** [comment]
You talking about fix-w3tc or official w3tc?

**Comment by casbboy** [comment]
I'm using fix-w3tc. 
![w3t](https://cloud.githubusercontent.com/assets/17091513/19707254/6bea76ee-9acb-11e6-844c-44c0ad91f85a.jpg)

**Comment by amiga-500** [comment]
Hi @casbboy 

1. Because _default.include.xx_ indicates you are using Minify's manual mode, do you have any files that no longer exist but still showing as listed under _Performance > Minify > JS/CSS File Management_ sections?

2. Are you seeing these 404's via your log files only (external sources are requesting them) or are you seeing these files embedded within your html pages (so when these pages go to access them they result in 404s)?

3. And just as a heads-up, if you want to hide the update notification message (that monster-sized yellow thingy in your attached image) you can do so via _Performance_ > _General Settings_ > _Miscellaneous_ .  See the attached pic below.  It's unchecked by default.

![f06611a0-866f-11e6-976e-e0709a0c478e](https://cloud.githubusercontent.com/assets/5191497/19020360/369944f2-8874-11e6-9c9d-4704aebddf7e.jpg)

**Comment by casbboy** [comment]
Thanks for the response.

1. I go to the minify section and have confirmed all of the files listed under JS and CSS still exist. I saved settings and cleared cache. Still getting two requests on each file and 404. It's weird. I see this in the console. in the source code I see the file attempted to be called in the footer:


<link rel="stylesheet" type="text/css" href="https://cdn.traileraddict.com/article/wp-content/cache/minify/000000/0ec95/default.include.301799.css" media="all" />

The other file is the last called before the footer.

2. The 404s are coming from own source code. I try to open directly to be sure and they do not exist

You can see sample here: http://www.traileraddict.com/article/

3. thanks for advice!

Cheers
Ryan

**Comment by amiga-500** [comment]
I believe the reason it is 404'ing is because i notice it is attempting to retrieve them via the "https" protocol which is using an invalid certificate, causing it to fail within a browser that hasn't allowed the exception.

If your server provides it you could use "Let's Encrypt" to get a free validated certificate for your site so all https requests will work.

**Comment by casbboy** [comment]
Yeah, I thought that could be it as well. It is so weird. If i were to remove a single include and put it back (like a JS file) in Minify, would it build a new JS to include on page.

**Comment by casbboy** [comment]
I removed the "Enable" checkmark and cleared cache. I loaded the page and no 403 errors. I then re-enabled the css to test, and it looks like it created another CSS file name for the combining of css.

/article/wp-content/cache/minify/000000/0ec95/default.include.e9c856.css

I logged in on FTP to see if that file was in that folder, and it was not.

**Comment by amiga-500** [comment]
> /article/wp-content/cache/minify/000000/0ec95/default.include.e9c856.css
> I logged in on FTP to see if that file was in that folder, and it was not. 

So this new file (e9c856) doesn't exist via FTP neither on your local server nor your CDN, correct?  You only see the new file request (and failure) within your webpage via a browser console?

**Comment by amiga-500** [comment]
Can you check if an _error_log_ file exists in your root that might give a hint of write issues  (not sure what server you are using).

Also can you enable debug mode via `wp-config.php`:
```php
define('WP_DEBUG',true);
// * Enable/Disable Debug logging to the /wp-content/debug.log file
define('WP_DEBUG_LOG',true);
// * Enable/Disable display of errors and warnings in HTML output
define('WP_DEBUG_DISPLAY',false);
if (WP_DEBUG)@ini_set('display_errors',0);
```
This will create a **debug.log** file within your _wp-content/_ directory as errors pop up.  Then try removing a file from the include again and trigger a new minify to generate.  Hopefully something will be written out to the debug file.

**Comment by casbboy** [comment]
I did that and nothing shows in the debug.log file that is related to plugin. could it be a permissions issue in the directory?

**Comment by casbboy** [comment]
The director does show that these were made today: 

-rw-r--r--  1 80  1006  13 Oct 26 03:47 default.include-footer.js.id.old
-rw-r--r--  1 80  1006  13 Oct 26 04:34 default.include.css.id
-rw-r--r--  1 80  1006  13 Oct 26 04:34 default.include.css.id.old

Then I change it, empty cache and page cache and the directory shows updated again:

-rw-r--r--  1 80  1006  13 Oct 26 03:47 default.include-footer.js.id.old
-rw-r--r--  1 80  1006  13 Oct 26 04:44 default.include.css.id
-rw-r--r--  1 80  1006  13 Oct 26 04:44 default.include.css.id.old

You will see the recently updated.

**Comment by casbboy** [comment]
I've had to just leave it disabled to ensure no 404 errors. I thought it could be a permissions things, but thinking seeing those files updated and created above throws that idea out.

Should I maybe uninstall and re-install? But will I lose all my settings?

**Comment by amiga-500** [comment]
Hi @casbboy ... Very strange problem.  I have never seen this occur before.  I can't even duplicate the problem on my end.  When checking the w3tc code i notice when it writes out it then reads it back in to compare.  If it doesnt match it deletes the file.  I wonder if that may be the problem.  Not sure.

1. Under  _**Performance, General Settings > Minify**_ ... i assume _Minify Cache Method_ is presently set to `Disk`.  What is _JS Minifier_ and _CSS Minifier_ set to?

2.  Let's do a temporary test.  Can you pull up _**w3-total-cache/lib/Minify/Minify/Cache/File.php**_ and replace line **41-68** (shown below): 
    ```php
    public function store($id, $data) {
        $path = $this->_path . '/' . $id;
        $flag = $this->_locking ? LOCK_EX : null;
        if (is_file($path)) {
            @unlink($path);
        }
        if (!@file_put_contents($path, $data, $flag)) {
            // retry with make dir
            w3_mkdir_from(dirname($path), W3TC_CACHE_DIR);

            if (!@file_put_contents($path, $data, $flag))
                return false;
            if (is_file($path . '.old')) {
                @unlink($path . '.old');
            }
            @file_put_contents($path . '.old', $data, $flag);
        }
        // write control
        if ($data != $this->fetch($id)) {
            @unlink($path);
            return false;
        }
        return true;
    }
```
with this:
   ```php
 public function store($id, $data) {
        $path = $this->_path . '/' . $id;
        $flag = $this->_locking ? LOCK_EX : null;
        if (is_file($path)) {
            @unlink($path);
        }
        error_log("**Call to store() - Request to store: $path");
        if (!@file_put_contents($path, $data, $flag)) {
            // retry with make dir
            w3_mkdir_from(dirname($path), W3TC_CACHE_DIR);
            if (!@file_put_contents($path, $data, $flag))
                return false;
            if (is_file($path . '.old')) {
                @unlink($path . '.old');
            }
            @file_put_contents($path . '.old', $data, $flag);
        }
	else
	    error_log("**Call to store() - Successfully stored: $path");
        // write control
        if ($data != $this->fetch($id)) {
            @unlink($path);
            return false;
        }
        else
	    error_log("**Call to store() - Successfully verified: $path");
        return true;
    }
```
3. Now re-enable Minify and try to get it to write out a css/js minified file(s) to disk.  The store() function you just modified above is where your minify files pass through to get written out locally.  If there is a problem it could be in here.  What this temporary change will do is write out some stuff to your log file (either _error_log_ or _debug.log_ depending how you have things configured) to give us a hint if something is going wrong when it gets to a non "_.id_" file.

4. Post the relevant lines from your log file when you see them.  The lines are prefixed with: 
**Call to store() -**

Thanks again
Kimberly

**Comment by amiga-500** [comment]
And although we discovered that the "id" files' dates were being modified and should indicate your permissions are fine, i still have to ask:  is every parent directory permission of your target folder **755** ?

Thanks again

**Comment by casbboy** [comment]
Sorry for the delay. We've been working on some migration stuff. Let me get on this.

**Comment by casbboy** [comment]
Looks like all the directories in cache are 751 permissions.

**Comment by amiga-500** [comment]
> Looks like all the directories in cache are 751 permissions.

Thanks for the info. Has this minify issue been an ongoing problem for you or did it just recently start?  

And if its not too much trouble can you modify your _File.php_ file as discussed [4 messages back](https://github.com/szepeviktor/fix-w3tc/issues/161#issuecomment-256507784)?

**Comment by amiga-500** [comment]
Havent heard back from you in a while.  Any new updates (discoveries, reveals, hints)?

**Comment by casbboy** [comment]
Hello!

No, we just noticed the minify issues after going from the Updated Plugin over to the Fix w3tc version. I'll have an update on the file.php fixes in next 12 hours.

**Comment by amiga-500** [comment]
Hi again,

Can you uncheck (deactivate) _Performance > Minify >_**_Rewrite URL structure_**

and see if that fixes your problem?

Let me know
Kimberly

**Comment by amiga-500** [comment]
Hi again @casbboy

Can you uncheck (deactivate) Performance > Minify > Rewrite URL structure and see if that fixes your problem?

Although we looked at it briefly, it still seems your problem is related to permissions because I was only able to recreate your problem identically today, including file requests for 404'ed css/js files showing up twice and js.id/css.id files being written (and only them) in the minify directory, when some other parent directory down the chain had a permission of say 744 or more strict.

For example, when i set wp-content to 744, but say wp-content/cache or even wp-content/cache/minify was still 751 your problem was still there. However, if i then put back wp-content to 751 it all worked again (no more 404s) -- the real css/js files were now able to write within the minify directory fine.

In a previous reply you said: "all the directories in cache are 751 permissions.". Can you go one step further and check the permissions on all parent directories that lead to cache too? We need to makes they are all 751.

Take note how when "Rewrite URL structure" is unchecked/deactivated the missing js/css files are now written within the minify directory. This seems to indicate that w3tc is doing a late permissions check on 1 or more directories (for the Rewrite Url request) to confirm things before writing the js/css files, but isn't doing this check for the id files. Meaning, w3tc is being picky even though it doesnt have to be. I'll eventually hunt down where that check is being done because i am too damn curious. But for now, i am betting the unchecked/deactivated "Rewrite URL structure" option will solve things for ya.

Let me know
Kimberly

**Comment by casbboy** [comment]
I'll try that now, in regards to directories:

wp-content: rwxrwxr-x (775)
cache:  drwxr-xr-x (775)
minify: rwxr-xr-x (755)
000000: rwxr-xr-x (755)
0ec95: rwxr-xr-x (755)

It's weird though. One of my logins that I know belongs to the group now has no permissions, though the group still has permissions and my (FTP) login still shows as being part of the group.

**Comment by casbboy** [comment]
I changed all directories to 771, and all my permissions were okay. Tried minimizing again and still get 403. Though these files keep updating:

-rw-r--r--  1 80  1006  13 Oct 31 19:06 default.include-footer.js.id
-rwxrwx--x  1 80  1006  13 Oct 31 19:06 default.include-footer.js.id.old
-rw-r--r--  1 80  1006  13 Oct 31 19:06 default.include.css.id
-rwxrwx--x  1 80  1006  13 Oct 31 19:06 default.include.css.id.old

I'll try deactive rewrite now.

**Comment by casbboy** [comment]
I deactivated the "Rewrite URL Structure" and the 403 errors went away.

**Comment by amiga-500** [comment]
> I deactivated the "Rewrite URL Structure" and the 403 errors went away.

@casbboy  that's good to here.  At least you have that option to get minify to work.  Notice how the missing js and css files are now able to write in that folder now.  

And thanks for the extra details....You seem to be the only person i know that has seen this problem.  For me, this problem never occurs.  To simulate your problem I have to unconventionally modify my permissions.  But yet your folder permissions all seem fine (thanks for the share).  So far seem this all seems to indicate it's not a w3tc issue but some kind of server-side configuration thing, but i will need to keep diving in to see which lines of code are actually doing some kind of system check and failing -- from there we can then explore more system-level settings.

Anyway, at least you have a reliable way of getting minify to work now so that's good to know.

**Comment by casbboy** [comment]
Well,

And we did a quick swap install, which I'm thinking caused the strange error. I just renamed the original W3T plugin folder from FTP, then did the install of W3T Fix plugin through the WordPress upload console. 

Wasn't the cleanest fix, but we were panicked with the new version of W3T causing 503 errors all over the place.

Thinking this may have had something to do with the issue.

Also, the site is running on NGINX.

**Comment by amiga-500** [comment]
Ahh nginx.  Curious, what rules do you have in your _nginx.conf_ file related to w3tc?  Although i primarily only use apache and as such w3tc automatically updates my apache .htaccess file with everything i need for minify and page caching, if i recall, for nginx you are to manually update your nginx.conf file by hand with the rules that w3tc needs to be able for full minify and caching (disk enhanced mode).  I could be mistaken..its been a while since i've dealt with nginx.  So i am curious what rules are in that file and if there are possible mistakes.

Do you see something like **w3tc_rewrite_test=1** in there?

Thanks for the info.

**Comment by casbboy** [comment]
I had to disable it all for some dev work with Cloudflare Rocket Loader, but brought back Minify Cache and Page Cache:

```
# BEGIN W3TC Minify cache
location ~ /article/wp-content/cache/minify.*\.js$ {
    types {}
    default_type application/x-javascript;
    expires modified 31536000s;
    add_header X-Powered-By "W3 Total Cache/0.9.4.5";
    add_header Vary "Accept-Encoding";
    add_header Pragma "public";
    add_header Cache-Control "max-age=31536000, public";
}
location ~ /article/wp-content/cache/minify.*\.css$ {
    types {}
    default_type text/css;
    expires modified 31536000s;
    add_header X-Powered-By "W3 Total Cache/0.9.4.5";
    add_header Vary "Accept-Encoding";
    add_header Pragma "public";
    add_header Cache-Control "max-age=31536000, public";
}
location ~ /article/wp-content/cache/minify.*js\.gzip$ {
    gzip off;
    types {}
    default_type application/x-javascript;
    expires modified 31536000s;
    add_header X-Powered-By "W3 Total Cache/0.9.4.5";
    add_header Vary "Accept-Encoding";
    add_header Pragma "public";
    add_header Cache-Control "max-age=31536000, public";
    add_header Content-Encoding gzip;
}
location ~ /article/wp-content/cache/minify.*css\.gzip$ {
    gzip off;
    types {}
    default_type text/css;
    expires modified 31536000s;
    add_header X-Powered-By "W3 Total Cache/0.9.4.5";
    add_header Vary "Accept-Encoding";
    add_header Pragma "public";
    add_header Cache-Control "max-age=31536000, public";
    add_header Content-Encoding gzip;
}
# END W3TC Minify cache

# BEGIN W3TC Page Cache core
set $w3tc_rewrite 1;
if ($request_method = POST) {
    set $w3tc_rewrite 0;
}
if ($query_string != "") {
    set $w3tc_rewrite 0;
}
if ($request_uri !~ \/$) {
    set $w3tc_rewrite 0;
}
if ($http_cookie ~* "(comment_author|wp-postpass|w3tc_logged_out|wptouch_switch_toggle)") {
    set $w3tc_rewrite 0;
}
set $w3tc_rewrite_preview "";
if ($http_cookie ~* "(w3tc_preview)") {
    set $w3tc_rewrite_preview _preview;
}
set $w3tc_enc "";
if ($http_accept_encoding ~ gzip) {
    set $w3tc_enc _gzip;
}
if (!-f "$document_root/article/wp-content/cache/page_enhanced/$http_host/$request_uri/_index$w3tc_rewrite_preview.html$w3tc_enc") {
  set $w3tc_rewrite 0;
}
if ($w3tc_rewrite = 1) {
    rewrite .* "/article/wp-content/cache/page_enhanced/$http_host/$request_uri/_index$w3tc_rewrite_preview.html$w3tc_enc" last;
}
# END W3TC Page Cache core


# BEGIN W3TC Page Cache cache
location ~ /article/wp-content/cache/page_enhanced.*html$ {
    expires modified 60s;
    add_header X-Powered-By "W3 Total Cache/0.9.4.5";
    add_header Vary "Accept-Encoding, Cookie";
    add_header Pragma "public";
    add_header Cache-Control "max-age=60, public";
}
location ~ /article/wp-content/cache/page_enhanced.*gzip$ {
    gzip off;
    types {}
    default_type text/html;
    expires modified 60s;
    add_header X-Powered-By "W3 Total Cache/0.9.4.5";
    add_header Vary "Accept-Encoding, Cookie";
    add_header Pragma "public";
    add_header Cache-Control "max-age=60, public";
    add_header Content-Encoding gzip;
}
# END W3TC Page Cache cache
```

There you have it :)

**Comment by amiga-500** [comment]
Interesting.  Seems you are missing the W3TC Minify Core part in your nginx config:

```nginx
# BEGIN W3TC Minify core
rewrite ^/article/wp-content/cache/minify.*/w3tc_rewrite_test$ /article/wp-content/plugins/w3-total-cache/pub/minify.php?w3tc_rewrite_test=1 last;
set $w3tc_enc "";
if ($http_accept_encoding ~ gzip) {
    set $w3tc_enc .gzip;
}
if (-f $request_filename$w3tc_enc) {
    rewrite (.*) $1$w3tc_enc break;
}
rewrite ^/article/wp-content/cache/minify/(.+/[X]+\.css)$ /article/wp-content/plugins/w3-total-cache/pub/minify.php?test_file=$1 last;
rewrite ^/article/wp-content/cache/minify/(.+\.(css|js))$ /article/wp-content/plugins/w3-total-cache/pub/minify.php?file=$1 last;
# END W3TC Minify core
```
Not sure if you had removed it or just never had it in.  But i believe w3tc needs it.  Would you try putting it in and of course this is assuming you'd still prefer to use minify while leaving activated the "_Rewrite URL Structure_" 

Thanks again
Kimberly :octocat:

**Comment by casbboy** [comment]
Hey Amiga,

It was actually in there. I just removed it (it was asked to be removed) after disabling the minify.
