### ISSUE TITLE
[0.9.5] Current W3 Cache fails to connect to CDN on load balancer set ups

### ISSUE THREAD

**Issue by doodirock** [szepeviktor/fix-w3tc#164]
Wanted to see if you guys have some accross this when trying to fix the many broken issues with the latest w3.  I've posted several times in the support forums, but it looks like the original author is simply not interested.  

The issue seems to occur in load balancer set ups.  We currently use Rack Space as our CDN and the new wizard introduced allows you to set up all settings fairly easily.  However after a while your settings just stop working and W3 fails to authenticate against the CDN.  Even if you have the master.json on both servers after a while the authentication from the CDN will fail. 

The only way to get it to work again is to re-authenticate over and over. For some reason, even though all the settings are stored on the JSON file they are not being read when it goes to authenticate against the CDN.

Our team has tried to debug, but there doesn't seem to be a great reason why this is happening.  Was wondering if you guys had come across this yet.  Keep in mind this issue has been reproduced on all our sites (15 of them).

Step to reproduce:

1) Fill out settings for RackSpace CDN.
2) Click test and verify tests passes (it does)
3) Add master.json to both load balancers.
4) wait......
5) Click test again and you get authentication failed.  All settings are still there and saved in master.json.
6) Re-authenticate again while flipping over your desk and screaming to the gods.
7) Repeat this process every few hours.

**Comment by nigrosimone** [comment]
sorry for the delay @doodirock, but here we are few guys, no one has a similar web-server configuration for reproduce the problem and fix it. 

but keep us updated! if you find the problem, we will be happy to fix it!

I'm sorry can't help you! :(

**Comment by amiga-500** [comment]
Yea i really have an itch to want to fix this bug -- and i am sure i would be able to identify the issue and fix it -- but sadly my problem is i just have no way of being able to have access to a RackSpace CDN setup with load balancers :( ... wow that is quite the set up you got there @doodirock 

I went as far as contacting RackSpace several days back when i first saw this bug post.  I asked about getting some limited free access to their RackSpace CDN and load balancers so i could officially fix this w3tc bug since it would benefit them as a business for w3tc to properly work for their servers.  Sadly, i did not get a reply (yet? still hoping) :( 

@doodirock  does this problem only happen with RackSpace or does it also occur when using Amazon CloudFront, and/or CloudFlare too?  

From your description of the problem it sounds to me like a timeout issue with the authenticated key that w3tc is obtaining but w3tc is not phoning back home periodically enough (or at all) or not setting the necessary flag(s) that RackSpace expects  for it to keep the key from expiring.  This would probably explain why it expires after xx amount of time requiring you to return to the test page over and over again.

**Comment by nigrosimone** [comment]
hey @rackspace guys, we need a dev account for fix this issue!

**Comment by doodirock** [comment]
Wow!  First off thank you all so much for trying to help.  

@amiga-500 As far as i know its only Rackspace, but that is only because we currently only use Rackspace as our file serve.  There are actually two types of CDN with RS.  One is their file storage (which is what we use) and the other is their CDN

https://support.rackspace.com/how-to/differences-between-rackspace-cdn-and-rackspace-cloud-files/

I agree with your assumption.  From what we can tell, after you make your first authentication, w3Cache simply doesnt re-authenticate and assumes your connection is valid to Rackspace.  I haven't dug deep into the code, but I assume it needs to send auth information with every request or else it fails.

**Comment by amiga-500** [comment]
Oh hi @doodirock  ... glad to see you're here!  



I'm going to snoop around the code and see what i turn up.  Right now i know w3tc does its RackSpace authentication within the `authenticate()` function inside the _Cdn_Rackspace_Api_Tokens.php_ file

I've also located Rackspace's dev site and presently have their [authentication procedure](https://developer.rackspace.com/docs/cloud-identity/v2/getting-started/authenticate/) up and see w3tc is using their steps to authenticate.  So that is a good sign that i am on the right track, and that somewhere in this area something is failing.  

I will do a thorough compare soon.  Because i won't have access to test things it will become difficult for me to better pinpoint where things fail.  So i might have to keep spamming you with questions and experiments you can test on your Development box.

In the meantime:

1. When it fails does it give more information about the fail?  Or does it simply just say "Can't Authenticate"?  Is there more text said?  According to the code it throws exception error messages about reasons for failure which gets appended to "Can't Authenticate".  This will help narrow where the problem is occurring.  

1. And where does it say this message?  Are you you specifically using: _Performance > CDN > Configuration > Authorise_ (button)?  I just want to make sure we are on the same page.

1. You mention you click "Test" to authenticate and it passes, but you wait for a bit and click the same "Test" button and it reports back as failed.  How much time has to pass before it fails?  Is it always the same amount of time?  What happens if you stay active on the admin page (feeding more content to the CDN) -- does the authentication still fail at the same amount of passed time?

Thanks for the info.  I have more questions but i will just build them up when i eventually roam through RackSpace's API.  Interestingly, i do see an "expires" field in the RackSpace authentication responses (i'm still on their API site).  I wonder if w3tc isn't renewing the authentication prior to the expire...and if that expire time matches the times when you see your problems.  And i wonder if one needs to remain active with their authentication for their authentications to not expire or if it's a hard expire, forceably requiring w3tc to make a behind-the-scene's authentication check.  In either case it is a simple w3tc fix.  But i'm jumping ahead of myself.

Thanks for the info
Kimberly

**Comment by amiga-500** [comment]
@doodirock you around?  Still waiting.

**Comment by doodirock** [comment]
Thanks Amiga!

1) The error given is **Error: Unable to write object (Failed to reach API endpoint, got unexpected response Unauthorized)**.

2) This message displays when you click the TEST button on the CDN page.  You get no other errors out side of checking with TEST.

3) My best guess is that it's random.  If re-fill in the info and authenticate I can freely upload images for a long while.  I've tried to force it to break by closing my session, loging out, and clearing cookies.  In this case if I go back right away it still works.  Im tracking it today to check every few minutes to get a better sense of when it fails.  I'll get back to you with a closer time.

4) Once it fails, it stays failed forever.  In order to get it to work you have to re-enter all of the data again.  The odd part is that all the data is still there and displayed.  You basically click Reauthorize and put in the same settings that are already on the page.  After that if you hit test it passes and you're able to upload content again.

5) Will do

6) I'll have to see if Rackspace has logs and get back to you.  I"ll let you know ASAP.

Actually the expires thing is exactly that I thought was happening and I'm about 99% certain this is the problem.  IMO w3 assumes that it only needs to auth once but after that doesn't renew.  So it works for the initial set up, but once the token expires it breaks and we have to auth all over again.

**Comment by amiga-500** [comment]
Hi @doodirock thanks for the info.  You can skip step 5 for now (if it's not too late..however, if u already did and have details please share still).  I will give you some other code instead.  Your error message has me looking in another area now.

**Comment by FoxProf** [comment]
Hey folks,

We have exactly the same issue since the update and here's what we know:

We have a load balanced live site and its companion copy dev site that is not and have same issue with both so we do not think it's balancer related.

Rackspace API details that an authenticaton token is supplied and expires after 24hrs.  This has been timed since yesterdays authentication and I can confirm the test fails like clockwork and re authentication is required after 24hrs.

Agree with amiga-500 the plugin has stopped (since the update) re-authenticating prior to the 24hr timeout.

Regards all

**Comment by FoxProf** [comment]
@doodirock 
If you are having to re-enter the credentials each time this is most likely a side effect of your balancer doing its thing.  Set your LB to drain connections for your secondary server(s) so it's only sending traffic to your main web server then update all w3 CDN settings and afterwards rsync the master.json/.php/etc (in fact I just do the whole dir: wp-content/w3tc-config) from main over to them and bring all up active again.  This works for us and settings are retained across all servers for the authentication.  I repeat this action if i need to make changes and have them persist across all servers (plus by limiting connections while configuring you are sure which set of config files on which server the plugin has updated).

**Comment by amiga-500** [comment]
Hi @FoxProf! Very much appreciated for all the info!  It helps a lot!  With your details and what @doodirock is saying i've conjured up a solution that will hopefully fix the problem. :pray:

@doodirock (and if you want to as well, @FoxProf) open up the file: **_Cdn_Core.php_**.  We are going to make a few quick & simple changes.

Line **509** is:
```php
break;
```
Replace it with:
```php
(new CdnEngine_Mirror_RackSpaceCdn($engine_config))->_on_new_access_requested_api();
break;
```
Line **529** is:
```php
break;
```
Replace it with:
```php
(new CdnEngine_RackSpaceCloudFiles($engine_config))->_on_new_access_requested_api_files();
break;
```

Let me know how it turns out.

Cheers
Kimberly :octocat:

**Comment by doodirock** [comment]
I'll check it out now!

**Comment by FoxProf** [comment]
Just tried this against our dev as I have left that in the unauthorised state to test but just breaks the CDN config page (comes up blank) so difficult to tell if anything happened.  Have reset changes to get the page back but no apparent change.

**Comment by amiga-500** [comment]
thanks for the info @FoxProf....sorry about that...one thing i didnt do was test out the CDN part vs doodrock's Cloud Files part (which i was testing).  I will see why the CDN part breaks in an hour (distracted with something else).  I'm sure it was some minor mistake.

ttyl.

**Comment by amiga-500** [comment]
Hi again @FoxProf ... just ran a quick test and seemed to work fine.  No blank page.  I assume you copy/pasted the lines precisely as shown above.  Curious..in your error_log file what is the logged php error message?

**Comment by FoxProf** [comment]
Hmm, did cut and paste into the places prescribed but you are right have PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in the log so mucked something up lol :)

**Comment by FoxProf** [comment]
Been a while since I did PHP coding :) but I have changed mine to:

Line 509:
$obj = new CdnEngine_Mirror_RackSpaceCdn($engine_config);
$obj->_on_new_access_requested_api();

Line 530:
$obj = new CdnEngine_RackSpaceCloudFiles($engine_config);
$obj->_on_new_access_requested_api_files();

and success! :)

CDN page back and test passed without even using reauthorise button so looks good so far :)

I'll have a good run through the dev site tommorow to check.  Probably should go home lol so night all and great job!

**Comment by amiga-500** [comment]
That's awesome to hear it's now working!  Seems to indicate your PHP version is less than 5.6.  My apologies.  Living in my bubble i had incorrectly assumed everyone was using 5.6+.  If all goes well with the tests then i will modify the syntax (for the release) to work under all php versions.

**Comment by doodirock** [comment]
Incredible news!  I can't wait to test it out. I'll give feedback asap. You are the best.

**Comment by doodirock** [comment]
So i put in this fix on the original w3 or download fix-w3tc and apply the fix there?

**Comment by amiga-500** [comment]
@doosirock, in the original w3 v 0.9.5.1 

I assume that is the one you've been using all this time. There is a branch in fix w3tc (not master) that applies fixes to that official version which is where I will place this fix later

**Comment by doodirock** [comment]
Perfect thanks.

**Comment by doodirock** [comment]
We're running it on stage and so far so good.  I'll let you know tomorrow if things stick.  Thank you so much for your incredible help.

**Comment by FoxProf** [comment]
Morning all,

Not attempted any reauthorise but uploads/deletes/display all seem working as expected, just need to wait past 24hrs for the final check but appears we have a winner :)

Great job Kimberly and all concerned, IT teamwork at it's best!

**Comment by FoxProf** [comment]
24hrs well and truly passed and the CDN connection continues to work :)

However a quick question: Is this reauthorising on every page access (or for each CDN served item on a page) and if so would that create a noticable lag overhead on busy sites?

Bear in mind that this fix although working may just be plastering over the cracks and the actual fix will be (as Kimberly stated above) where the expiry time is stored and checked if authentication is actually required i.e. 24hrs nearly up.

**Comment by amiga-500** [comment]
Hi @FoxProf ... hey that's great to know it works officially!  :satisfied: 

How it works is it reauthorizes when an API action is to be performed on the remote CDN (ie. upload, delete, and purge are the 3 commands w3tc does).  However, when a request to say upload 10 files is made only 1 re-authorization request is done, not 10.  Going further, when a queue of things is to be performed (via the _queue_process()_ function it only does a single re-authorization and then performs the entire queue collection.  So, if a queue contains a large collection of uploads, deletes, and purges they all get done after performing a single re-auth request.  So that's good.  By coincidence this current fix seems to take a similar approach to the previous version of W3TC (ie, v0.9.4.x) when i snooped in that earlier version just now.  So from what i can tell it doesn't look like you will see any lag overhead on a busy site at all.

For the fun of it though, because i now have official confirmation that the problem has been solved (thanks @FoxProf) i will just proceed with adding the expiration check too (my original plan) simply because it's easy to do and it will add a tiny bit more efficiency to this CDN process :thumbsup: .  I'll do so later today (or tomorrow) since there is no longer a rush :bowtie:

Cheers
Kimberly :octocat:

**Comment by doodirock** [comment]
Thanks so much for the help. Confirmed on my end as well!

**Comment by dan-at-unkubed** [comment]
Hi all,

We have been having this same issue since the October 2016 update as well.  After doing some digging, and bothering the Rackspace Cloud guys too much, I finally found this thread on Jan 5, 2017, read through it, applied the changes to our site.  Everything seemed to be working correctly just like the other two participants in this conversation.

Today the plugin stopped working though, and I went digging.

First, some info.

We're hosting our site through the Google Cloud on a 2-server load-balanced system.  PHP version 5.6.29-0+deb8u1.  The CDN solution we're using is Rackspace Cloud Files (we used to host the site from Rackspace, but we moved it and haven't moved the cdn service yet). We have W3TC version 0.9.5.1 and Wordpress 4.5.3 installed on our site.

Everything about this ticket is exactly the problem that we were seeing. I made the suggested changes back on Jan 5th, as I mentioned.  Today, the plugin stopped working and we noticed because it was not changing the asset urls from the site url (www.sitename.com) to the specified cdn url (cdn.sitename.com).  So, a lot of our images and functionality were broken on the site because those assets were trying to load from the site server instead of the cdn server, which for a load-balanced system doesn't always work.

On the admin side, when I went to the CDN settings page within W3TC, I found it to be blank.  When I removed the 4-line fix in the Cdn_Core.php file suggested above, everything started working again.

I went searching through our error logs to see if I could see anything obvious, and I found an 800MB file with loads of errors that nearly all looked like this:

[17-Jan-2017 17:10:00 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Username or api key is invalid.' in wp-content/plugins/w3-total-cache/Cdn_RackSpace_Api_Tokens.php:138
Stack trace:
#0 wp-content/plugins/w3-total-cache/Cdn_RackSpace_Api_Tokens.php(27): W3TC\Cdn_RackSpace_Api_Tokens::_decode_response(Array)
#1 wp-content/plugins/w3-total-cache/CdnEngine_RackSpaceCloudFiles.php(84): W3TC\Cdn_RackSpace_Api_Tokens::authenticate('sitecdn', 'g034efae12904d5...')
#2 wp-content/plugins/w3-total-cache/CdnEngine_RackSpaceCloudFiles.php(66): W3TC\CdnEngine_RackSpaceCloudFiles->_on_new_access_requested()
#3 wp-content/plugins/w3-total-cache/Cdn_Core.php(535): W3TC\CdnEngine_RackSpaceCloudFiles->_on_new_access_requested_api_files()
#4 wp-content/plugins/w3-total-cache/Cdn_Plugin.php(1097): W3TC\Cdn_Core->get_cdn()
#5 wp-content/plugins/w3-total-cache/Cdn_Plugin.p in wp-content/plugins/w3-total-cache/Cdn_RackSpace_Api_Tokens.php on line 138

beginning back on Jan 5, 2017 (when I made the suggested changes) and continuing through today.

The crazy thing is that we haven't had an issue with the plugin until today, nearly two weeks later.  The cdn uploader has worked fine. The api key hasn't peremptorily expired.  No error messages visible on the site.  Once I got the admin-side cdn settings page working, I tested the connection and everything seems to work for now.

I'm anticipating that we'll go back to the case where the api key is apparently "expiring" because I've put the plugin code back into the condition where it was before we noticed any of this mess happening or making any changes.

Is there any way I can get you to look into this again?  Or perhaps, for those others that have benefited from the code changes above to check their error logs to see if they're also getting these fatal errors from php?

Thanks.

**Comment by nigrosimone** [comment]
@dan-at-unkubed official w3 total cache has [just release](https://it.wordpress.org/plugins/w3-total-cache/changelog/) an update (0.9.5.2). Maybe, you have autoupdate enabled and now you are on official 0.9.5.2 instead of w3tc-fix version?

**Comment by dan-at-unkubed** [comment]
Nope.  It's definitely 0.9.5.1.  I can see the line:

There is a new version of W3 Total Cache available. View version 0.9.5.2 details or update now.

On the Wordpress plugins page.

**Comment by nigrosimone** [comment]
in the [changelog ](https://it.wordpress.org/plugins/w3-total-cache/changelog/) of 0.9.5.2 i see:

- Improved compatibility with Rackspace Cloud Files

**Comment by dan-at-unkubed** [comment]
Will try updating then.

**Comment by nigrosimone** [comment]
maybe (i don't have checked), version 0.9.5.2 has all our fixes.
