### ISSUE TITLE
Question : How to count impression and click through rate when using w3tc

### ISSUE THREAD

**Issue by todiadiyatmo** [szepeviktor/fix-w3tc#175]
Hi All,
I need suggestion on how best to count impression and click through rate  of an article when using this plugin, any hook / filter recommended to archive this 

Cheers !
Todi

**Comment by amiga-500** [comment]
Hi Todi!  Others can chime in too but i believe your options are either:

1. Google Analytics should work since it makes use of javascript. 
1. By hand you could code up using ajax (jQuery makes it easy) on your pages (you'd associate it to ever href on the page so it gets logged per click) and processing them within your _functions.php_ file
1. Install a WordPress impression/CTR logging plugin that makes use of ajax (most should have that feature) -- I knew i had a wp link some time back but i cant find it at the moment :(
1. Using w3tc' s [fragment caching](https://www.justinsilver.com/technology/wordpress/w3-total-cache-fragment-caching-wordpress/) feature -- but it would require you to switch to Disk: Basic :( 

Cheers
Kimberly :octocat:
