### ISSUE TITLE
Cache miss scenario, need help to find the cause of the problem relating to Cache getting missed every-time.

### ISSUE THREAD

**Issue by dharmang-gtl** [szepeviktor/fix-w3tc#179]
I am using W3 Total Cache in my existing website for a project and want to use this fork for php7 compatibility, once I replaced the plugin with this version the cache is generated as expected in the CACHE Directory but when the pages are visited/rendered every-time it executes the code and display page instead of the cached version. It means it misses the cache every-time and page life cycle gets executed as usual without any performance benefit.

I have defined constant to re-locate the cache directory in wp-config.php using:

`defined('W3TC_CACHE_DIR') || define('W3TC_CACHE_DIR', ABSPATH.'wp-content/XXXXXX');`

Also, I am getting following notice in admin side plugin list page:

> The Page Cache add-in file advanced-cache.php is not a W3 Total Cache drop-in. It should be removed.

**Comment by amiga-500** [comment]
### Questions

1. After modifying your _wp-config.php_ file are the cache files being generated inside your new cache location or are they still appearing in the old location?  As a heads up, just make sure you place your  _define('W3TC_CACHE_DIR', ABSPATH.'wp-content/XXXXXX');_ before` require_once(ABSPATH . ‘wp-settings.php’);` but after `define(‘ABSPATH’, dirname(__FILE__) . ‘/’);`

2. Are you using _Disk Enhanced_ or _Disk Basic_ for page caching?

3. If it's disk enhanced have you looked inside your .htaccess (i am assuming you are using an Apache server) to see that the rewrites are directing to your new cache location?

4. As for the _advanced-cache.php_ issue... are you using more than 1 caching plugin?  There might be a conflict.

Thanks for the info
Kimberly

**Comment by amiga-500** [comment]
Hi @dharmang-gtl 

### Questions

1. After modifying your _wp-config.php_ file are the cache files being generated inside your new cache location or are they still appearing in the old location?  As a heads up, just make sure you place your  _define('W3TC_CACHE_DIR', ABSPATH.'wp-content/XXXXXX');_ before` require_once(ABSPATH . ‘wp-settings.php’);` but after `define(‘ABSPATH’, dirname(__FILE__) . ‘/’);`

2. Are you using _Disk Enhanced_ or _Disk Basic_ for page caching?

3. If it's disk enhanced have you looked inside your .htaccess (i am assuming you are using an Apache server) to see that the rewrites are directing to your new cache location?

4. As for the _advanced-cache.php_ issue... are you using more than 1 caching plugin?  There might be a conflict.

Thanks for the info
Kimberly

**Comment by dharmang-gtl** [comment]
Hi @amiga-500,


1. The statement is at correct place with _ABSPATH_ defined and cache files are generated in the new location.

2. _Disk Enhanced_ cache method is used.

3. For apache server, .htaccess does not have the rewrites for redirection ( I will check that ) but it was working for older version of plugin.

4. Not other that _W3 Total Cache_ any caching plugin is used as of now.

**Comment by amiga-500** [comment]
@dharmang-gtl , thx for the info...very strange..i just checked now in a fresh install and it works fine for me and it also adds the necessary htaccess rewrites as needed.  it seems that is the problem...your rewrites aren't being added for some reason.  

under w3tc's dashoard it has a comaptibility check button..can u click it and see if you spot anything unusual?

do you see any changed in ur htaccess file done by w3tc at all? e.g. minified rewrites, browser cache?  anything?

**Comment by amiga-500** [comment]
btw, the advanced-cache,php error is indicating that, that file wasnt written by w3tc...could be a relic of something in the past that wasnt removed.   can you open the file and search for **_W3_PgCache_** ...if its missing that is your problem for that.  id recommend deleting that file and just refresh ur admin page to have it regenerated (assuming w3tc is still activated..otherwise just reactivating will regenerate it)

**Comment by dharmang-gtl** [comment]
In .htaccess file, there are some rules added by W3TC related to mod_expires, mode_deflate, mod_headers etc for Browser Cache but the mod_rewrite part is missing.

Deleting the advanced-cache.php file has worked now that error is gone.

**Comment by amiga-500** [comment]
@dharmang-gtl ,

I'm curious...is the _**mod_rewrite**_ module loaded on your server?  Putting aside the missing w3tc rewrite line, so you see any successfully deployed _rewritecond_ or _rewriterule_ lines at all being used in your htaccess?  Sounds like that module just isn't available.

Under _Performance > Dashboard >_ <kbd>Compatibility Check</kbd> button does it show for mod_rewrite?  For example here is mine:

![dashboard_w3_total_cache](https://cloud.githubusercontent.com/assets/5191497/20517381/d22178f6-b068-11e6-9635-81fdbddc6b62.jpg)

**Comment by dharmang-gtl** [comment]
Rewrite module is available and enabled, moreover, in our development environment, we checked that .htaccess is properly updated with Rewrite Rules but still the cache files are not generated when we access/refresh the pages.

The cache files were generated when we use sitemap.xml crawler available here: https://github.com/khromov/sitemap-cache-warmer

**Comment by amiga-500** [comment]
Hi again...needs some clarification:

1. Your last reply said "_.htaccess is properly updated with Rewrite Rules but still_"...so you're saying that Rewrite rules do exist in your htaccess file (and working) but none of these rules pertain to w3tc?  Or are you saying the rewrite rules generated by w3tc (starts with: _## BEGIN W3TC Page Cache core_ ) is found within your htaccess file but only on your development environment?

2. So your cache folder is currently empty and despite your having _Performance > General Settings > Page Cache_ = **Enabled** ... no files are every generated inside despite browser visits or using your sitemap crawler (btw: w3tc has WP-CLI support so you can flush, prime sitemap cache, etc from the command-line as an alternative approach)

3. If your rewrite rules are indeed being written successfully by w3tc on your dev side but no cache files are being generated then let's try a test by removing your custom CACHE dir line from wp-config (dont forget to _Empty all cache_ from dashboard beforehand so as to generate the new folder location structure).  I want to see if your cache files are able to generate inside the default location.

4. I assume your _Settings > Permalinks_ is something other than _Plain_, correct ?

This is an interesting issue to diagnose since i am unable to re-create the problem on my end.  Everything works fine on my side.  This is the first time i've heard your kind of problem  This seems to suggest its not w3tc but something in your environment (ie, permissions).

Thanks for the info

**Comment by amiga-500** [comment]
Forgot to add...

It's interesting that your _advanced_cache.php_ needed to be deleted to solve the other problem.  So it sounds to me your environment wasn't correctly cleaned prior to installation (e.g. a previous cache plugin was manually deleted instead of deactivated first, or a plugin author didnt remove their _advanced_cache.php_ prior to this e.g. the official w3tc 0.9.5.1's advanced_cache.php is not the same).  

That being said...if it's not too much trouble we should hunt around for other traces of the older cache plugin and possibly do a clean install of this because it doesn't seem like this is a bug with w3tc but could be some kind of plugin conflict or an environment setting.  

You might want to write down your config settings or use the export config feature (if necessary):

1. Delete all cache (via Dashboard > <kbd>Empty all Cache</kbd> button)
2. Deactivate the W3 Total Cache plugin
3. Delete the W3 Total Cache plugin from the Wp-content/plugins folder.
4. Remove this line from Wp-config file: define(‘WP_CACHE’, true)
5. Delete _advanced-cache.php, db.php, object-cache.php_ files found inside wp-content folder
6. Delete the entire _w3tc-config_ folder from the _wp-content_ folder.
7. Delete the _cache_ folder if it exists and your custom cache folder also within _wp-content_
8. Check your _.htaccess_ file.  If you see any code added by W3 Total Cache, remove it

Once that is out of the way and you reinstall then we can at least eliminate one other possible reason for why your problem was occurring.
