### ISSUE TITLE
W3TC plugin does not work after updating to WordPress 4.6.1 

### ISSUE THREAD

**Issue by timmen22** [szepeviktor/fix-w3tc#181]
Hi Al,

Last week I have updated my WordPress install to version 4.6.1. After updating the W3TC (fixed) plugin does not work like it should anymore. (Page cache does not working and debug information is not printed into the browser source).

**It is creating the following folders/files:**
wp-content/cache 
wp-content/config
wp-content/tmp (it does not create cached files over here, only the folder)
wp-content/index.html
wp-content/w3tc-config
wp-content/advanced-cache.php

**When I look at my .htaccess file it is only inserting the following tags:**
# BEGIN W3TC Browser Cache
...
# END W3TC Browser Cache

Even though pagecaching is enabled it does NOT generate the following tags in .htaccess"
# BEGIN W3TC PageCache
...
# END W3TC PageCache

When I enable debug information (PageCache checked) I do not see anything in the source of my browser. Before the update this was also working fine.

**My setup:**
Page cache - Disk (basic) enabled;
PHP Version: 7.0.12; 
Web Server: Apache2;
WP_CACHE define: Defined (true);

I already tried to reinstall the plugin. (By deleting all folders/files, resetting .htaccess and deactivating the plugin but nothing seems to work.)

Help is really much appreciated. 

Thanks!

**Comment by amiga-500** [comment]
Hi @timmen22 ... happy to help.  Firstly, it definitely works fine as i just tested a fresh install using PHP 7, Apache, with Disk basic using the most current fix-w3tc release (i even made sure to delete the _wp-content/cache_ and _wp-content/w3tc-config_ folders to be fair).  So it seems there is something else on your end that is causing the issue.  Hopefully we can pinpoint what that is.  Let me say in advance i apologize for all the questions that will undoubtedly follow.  For me, the issue is always trying to recreate the problem on my end -- it's never easy; it always works.  Once i do that, solving it is pretty straight forward.  

Secondly, the reason you don't see a _**#Begin W3TC PageCache**_ entry within your htaccess is because you are using "_Disk (basic)_" (thanks for the details btw).  That means it will be writing your cache files within _wp-content/cache/page/000000_ directory not inside _wp-content/cache/page_enhanced_ and as such does not use htaccess for that.  You will need to switch to "_Disk: Enhanced_" to see that .htaccess entry.

### Some questions for ya:

1. If i recall you were using the official w3 total cache v0.9.5.1 some time back.  I assume you switched over to fix-w3tc which is an enhanced v0.9.4.x.  We technically have a separate branch within this repo that serves as updates for the v0.9.5.x generation.  I just want to make sure we are dealing with the same generation.  My work tends to focus mostly on the 0.9.4.x generation but from time to time i do jump over to 0.9.5.x for bug fixes.  Under-the-hood they are both coded a bit differently.

2. Did it just stop working today or did it stop working after you upgraded to WP 4.6.1?

3. Did you change to PHP 7 recently and that is when the problem occurred?  Or was it working with PHP 7 before?  I am curious about your loaded php7 extensions.  For me i use: 
    * dom
    * gd
    * json
    * mbstring
    * mysqli
    * xmlreader
    * xsl
    * zip

     i cant recall which of these were the bare minimums required by w3tc but have these pre-loaded (via cPanel).

4. You mentioned _wp-content/tmp_ was being written.  That's strange.  The tmp directory should be written within _wp-content/cache/tmp_.  Are you sure the directory location you see is _wp-content/tmp_?  I wonder if that is a relic from your time with 0.9.5.x.  Can you delete it and see if it is re-created?  Is there a _wp-content/cache/tmp_ directory?

5. Same question as # 4 but with file: _wp-content/index.html_ ... the _index.html_ file should be within the _wp-content/cache_ directory.

6. Not sure if you are using the minified feature.  If so are these files successfully being written to: _wp-content/cache/minify/000000/_?

Thanks for the answers.  I'm sure there will be more questions.  Again, these questions are merely to help me generate the same conditions so I can hopefully see your problem on my end, making it easier for me to solve it.

Cheers
Kimberly.

**Comment by amiga-500** [comment]
Hi again @timmen22  ... haven't heard back from you in a bit.  I will leave this Issue open a little longer before assuming you got it successfully working and closing it.

**Comment by timmen22** [comment]
Hi Kimberly,

Excuse me for my late response but better late than never. 

1.	You are right. Earlier I was using the official  0.9.5.1 W3TC plugin. I switched over to fix-w3tc for the fixes and improvements. Before the WordPress update I was not having any problems with the fix-w3tc plugin. For testing I switched back to the official plugin, but that one was’t working either. However the official plugin does print html debug information into the browser (fix-w3tc does not). I inserted the debug info below, it might gives you helpful information.

``

``
2.	After I upgraded to WordPress 4.6.1 it stopped working.

3.	I was already using PHP 7 so that can not be the problem (Do you still want to know all the php extensions?).

4 & 5.	You are actually right. The folders and files I mentioned are written within wp-content/cache.

6.	After enabling minify in general settings the minify folder is created. However the folder is empty so I don’t think it’s working.

I hope this give you any clues. 

Thanks for your support.

With kind regards,

Tim

**Comment by nigrosimone** [comment]
Fix-w3tc write debug info only if WP_DEBUG in wp-config.php is TRUE

**Comment by amiga-500** [comment]
Hi @timmen22  ... hey not a problem!

Ok from your new details it definitely seems to indicate there's something within your environment that is causing the issue, not w3tc itself.  I can assure you w3tc works in wp v4.6.1 perfectly.  I also just ran it against the upcoming v4.7 (RC1-39355) and again: passed with flying colours (no errors; no warning; all working).

My apologies for this thing taking so long to figure out :hourglass:.  When it can't be re-created on our side, nor not having direct access to the problem itself, solutions take a lot longer.  As such, we have to throw things out there hoping something will narrow the view and better pinpoint the exact reason for the problem :pray:. Once the exact reason for the problem is known the solution is fairly quick & easy to conjure up :tada:

That being said, let's do some quick tests.

## 1. Debug Mode
As @nigrosimone mentioned in his reply above, let's enable debug mode on your side and see what bubbles up.  Before we do that, can you check inside your _**error_log**_ file for anything relevant to w3tc?

Ok, to enable debug mode we'll do so via  your _wp-config.php_ file.

**Change:**
```php
define('WP_DEBUG', false);
```
**To:**
```php
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', false);
define('WP_DEBUG_LOG', true);
@ini_set('display_errors',0);
```
This will create a file called **debug.log** inside the _/wp-content_ folder. Now, just run through your routine by attempting to make it cache and then check the _debug.log_ file to see if anything of interest was written.  Also, within the admin page, under w3tc's dashboard, click <kbd>Empty All Caches</kbd> (i figure this action may trigger something interesting in the log file).

## 2. Wordpress Default Theme
There are themes out there that do some funny stuff that might result in a hidden conflict with w3tc.  Can you temporarily change your theme back to one of Wordpress' default themes (ie, _twentysixteen, twentyseventeen, twentyfifteen_).  Now check caching.

## 3. Disable All Plugins
Let's now temporarily disable all other active plugins except for w3tc.  Now check caching.

## 4. Compatibility Check
Under _Performance > Dashboard_ there is a button at the top entitled: <kbd>Compatibility Check</kbd> Can you click that and paste the results here?  Scrub any sensitive details before you do post, of course.

## Questions
1. You mentioned your problem occurred when you upgraded to v4.6.1.  What was the version you were upgrading from?  4.6.0?  4.5.x?  I might need to revisit this if the above tests don't produce anything of value.

2. Only after the above tests don't result in any progress i may like to have you post (or email me) your w3tc-config file(s) (ie, 9.4.5.6 = _master.php+master-admin.php_, 0.9.5.1 = _master.json_) -- again, you'd want to scrub any sensitive private data from them before posting of course.  With those config details i'd set my side the same way with hopes of it somehow preventing caching (highly doubtful, but i want to eliminate all possibilities).

Cheers,
Kimberly :octocat:

**Comment by timmen22** [comment]
Hi Kimberly.

Great news! I managed to solve the issue.

Some how the following lines of code were commented out in wp-settings.php:

`if ( WP_CACHE && apply_filters( 'enable_loading_advanced_cache_dropin', true ) ) {
// For an advanced caching plugin to use. Uses a static drop-in because you would only want one.
	WP_DEBUG ? include( WP_CONTENT_DIR . '/advanced-cache.php' ) : @include( WP_CONTENT_DIR . '/advanced-cache.php' );
}`

After putting the lines of code back in page caching was working as it should. 

Once again, thank you for your effort. It is really much appreciated!

Best regards,

Tim
