### ISSUE TITLE
Use mysqli

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#183]
@nigrosimone Please add `define( 'WP_USE_EXT_MYSQL', false );` to wp-config.

**Comment by nigrosimone** [comment]
Too late for guy in italy! Tomortow i will try... but what is?

**Comment by nigrosimone** [comment]
@szepeviktor i've tried... nothing happened.

I have db cache enabled with APCu on FIX-W3TC master

**Comment by szepeviktor** [comment]
Ooops.

I mean for the tests.

**Comment by nigrosimone** [comment]
ah ok... but tests cover only "object cache".

**Comment by szepeviktor** [comment]
OK, but they use database doesn't they?

**Comment by nigrosimone** [comment]
Yes you are right... mhh, I need to understand how to change at runtime wp-config.php and create a separate set of test (with and without WP_USE_EXT_MYSQL).

**Comment by amiga-500** [comment]
Sorry to jump in...not sure what you guys are up to but if it helps @nigrosimone  you can look to w3tc's `wp_config_add_directive()` function (found inside: _PgCacheAdminEnvironment.php_ or _PgCache_Environment.php_) as a direct way on how one can successfully write to (or remove from) _wp-config.php_ since it's that very function that writes the `define('WP_CACHE', true);` to _wp-config.php_.  So i figure writing out `define( 'WP_USE_EXT_MYSQL', false );` would take on a very similar approach.
