### ISSUE TITLE
wp-cli cache type detection

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#184]
Could you guys help me how to detect object cache type and status?

I would contribute to:  https://github.com/wp-cli/wp-cli/blob/master/php/utils-wp.php#L206-L208

**Comment by amiga-500** [comment]
Hi Viktor (@szepeviktor)!  I may be misunderstanding what you need but i just wrote up something for ya:

```php
if ( defined( 'W3TC' ) )
{
	if ( class_exists( 'Dispatcher' ) ) { // for w3tc 0.9.5.x generation
		$config = Dispatcher::config();
	} else { // for w3tc 0.9.4.x generation (backwards compatibility)
		$config = w3_instance( 'W3_Config' );
	}
	
	$w3tc_objectc_type = $config->get_string( 'objectcache.engine' ); // can be either: file, apc (apcu uses the same name), eaccelerator, xcache, wincache, memcached, redis
	$w3tc_objectc_enabled = $config->get_boolean( 'objectcache.enabled' ); // can be either: true, false

        if ( strcasecmp( $message, $w3tc_objectc_type ) == 0 ) {
              if ( !$w3tc_objectc_enabled ) {
                    $message .= ' (user disabled)';
              }
        } elseif ( $w3tc_objectc_enabled ) {
              // external object cache does not match what is selected (and enabled) in w3tc e.g. APCU extension is loaded but user is using file object cache type
       }
}	
```
**_Note_**: you'd want to put this somewhere near the end of the `wp_get_cache_type()` function.  Because _wp-cli_ already checks for the external object cache types being loaded (except for _eaccelerator_) you can compare the function's populated _$message_ variable with _$w3tc_objectc_type_ (do a case-insensitive compare) and if they match and _$w3tc_objectc_enabled_ is true then you have your active object cache type name.  Oh, and also be aware that the _file_ object type returned to _$w3tc_objectc_type_ is the only type that is not an external object cache.

Because the `eaccelerator `object cache is supported by w3tc but `wp_get_cache_type() ` is unaware you might want to also add the following  just after the _LCache_ lines:

```php
// Test for eAccelerator object cache (https://github.com/eaccelerator/eaccelerator)
elseif ( function_exists(  'eaccelerator_put' ) ) {
      $message = 'eAccelerator';
}
```
Cheers
Kimberly

**Comment by szepeviktor** [comment]
Thank you.
