### ISSUE TITLE
Install instructions wrong for fresh installation

### ISSUE THREAD

**Issue by smerriman** [szepeviktor/fix-w3tc#204]
The install instructions for this plugin says to rename the plugin folder from w3-total-cache-fixed to w3-total-cache before installing. However, if you don't have an *existing* advanced-cache.php this fails completely - since the one provided by this plugin (in the wp-content/advanced-cache.php folder inside the plugin) refers to the w3-total-cache-fixed folder.

**Comment by amiga-500** [comment]
My apologies @smerriman ... i am currently updating the install instructions to reflect that NO renaming is required.  A number of things have changed in the release.  I just have been swamped with other things and hadnt updated details on this repo yet.  So to be clear you do not rename the folder.. u just keep the folder as: _**w3-total-cache-fixed**_.

Once again..sorry for the confusion.

Kimberly

**Comment by smerriman** [comment]
Wow. That's got to be the fastest support response ever :) Thanks!

**Comment by amiga-500** [comment]
Hi again @smerriman ... just a heads up.  Not sure which branch you're using on your end (v0.9.4.x or v0.9.5.x) but just wanted to point out that because the branch names have changed today, if you were using the v0.9.4.x then 3 files were modified to reflect this.  For the v0.9.4.x generation, these 3 files are necessary to ensure the "_new version available_" update notification messages will work on your WP Plugin page.

If you did download from this branch earlier then i figure those 3 files are stale on your end.  To save you time here's the latest of those 3 that you can just download and replace:

[w3-total-cache-fixed/w3-total-cache-fixed.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/w3-total-cache-fixed.php)
[w3-total-cache-fixed/updater.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/updater.php)
[w3-total-cache-fixed/inc/define.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/inc/define.php)

Cheers
Kimberly :octocat:
