### ISSUE TITLE
A Question on minified filenames

### ISSUE THREAD

**Issue by superpoincare** [szepeviktor/fix-w3tc#220]
I have a question on filenames of minified css/js files. 

Suppose a modify a css file's contents. Does W3TC change the filename? Doesn't look like it. Perhaps that's the reason for query strings. 

Autoptimize on the other hand generates a different filename and doesn't need a query string. 

Anyway, my issue is more of a question for discussion than reporting an issue. Glad if someone can help me on this.

**Comment by superpoincare** [comment]
Of course this question is for the automatic mode.

**Comment by amiga-500** [comment]
It's been a while since i worked on the minify section but if i recall it does change the file name ever so subtly when you clear the minify cache.  We had to [modify the behavior](https://github.com/szepeviktor/w3-total-cache-fixed/issues/13#issuecomment-247115768) of minified hashed names by postfixing a key version (hashed in) which is what results in a new overall name.

Try comparing minified file names (using a search box since it might be hard to spot) after clearing the minify cache..you should see a subtle difference.

**Comment by superpoincare** [comment]
Thanks Amiga. I did some experiments in the automatic mode. Changed the CSS file and found that clearing caches creates the right file but the filename is still the same.

**Comment by amiga-500** [comment]
Ahhh...what version of _w3-total-cache-fixed_ are you using?

Also...

when u say you "cleared the cache".  I assume you are doing so from within the Admin page or are you manually deleting the cache from a file manager (e.g. ftp)?

**Comment by superpoincare** [comment]
The 0.9.5.x. 

i think it's not really a bug but a feature, although I think it could be improved. 

The reason is that otherwise the plugin would need to check the hash each and every time. So the minified filename is named according to the name of the filenames (or something else). In addition, that's the reason the query string feature is given. The filename stays the same ... query string needs to be changed manually. 

The reason I intended to discuss is that something better might be done. Such as detection file changes (css or js) and then making this automatic.

**Comment by amiga-500** [comment]
Ahhh 0.9.5.x....the feature i was referring to is in our 0.9.4.x generation only.  I haven't added the name change feature into 0.9.5.x yet.  Sorry about that.  

I totally agree with you that minified filenames need to change.  At present though they do change for 0.9.4.x gen users (we maintain both versions but 0.9.4.x still gets the most attention because we still have several people  that depend on it..but we intend to shift all our features we keep adding to 094x to 095x eventually) but it doesn't do that based on file change but in fact it changes (subtly) when you clear the minified cache.  It was done to correct a major issue people were reporting in the wp support forum.  Took forever for us to figure out what was going on...but it was a fun challenge.

In the 0.9.5.x generation the minfied file name is simply a md5 hash of each of the filenames separated by commas: e.g., _file1.ext,file2.ext_

In the 0.9.4.x generation there is a slight difference.  The minfied file name is simply a md5 hash of each of the filenames separated by commas _and_ a postfixed minified version (to correct the major issue i discussed above): e.g., _file1.ext,file2.ext,ver=#_ ...this results in a slightly new filename on a minify cache clear.

I'm happy to provide more details as to why that is, or happy to discuss other approaches.

Another approach would be to expand the 094x approach by also including a _file-modified-time_ e,g,  _file1.ext=file-modified-time,file2.ext=file-modified-time,ver=#_  which when u delete or clear just your page cache but not the minified cache (or u just dont have page cache on) the minified file would be forced to have a new name when the js/css file(s) change.  It would still change the minified filename when u cleared the minify cache but it would also now change by simply modifying the the js/css file too -- but again, this would be dependent on the page cache being cleared (or manually deleted) so that the page when regenerated would need to form a new minified name and notice the file size has changed.  Not sure if this approach is overkill since the 094x approach will change the name already when u clear the minified cache -- so just duplicating this approach to 095x could be all one needs.

Cheers
Kimberly :octocat:

**Comment by superpoincare** [comment]
Very useful information @amiga-500. Lots to think about. Merry Christmas!
