### ISSUE TITLE
Ignore query string paramenters on page cache enhanced

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#221]
Currently W3 Total Cache use cached page in enhanced mode only if query string is empty, the rule is:
```
RewriteCond %{QUERY_STRING} =""
```
full code from .htaccess:
```
# BEGIN W3TC Page Cache core
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{HTTP:Accept-Encoding} gzip
    RewriteRule .* - [E=W3TC_ENC:_gzip]
    RewriteCond %{HTTP_COOKIE} w3tc_preview [NC]
    RewriteRule .* - [E=W3TC_PREVIEW:_preview]
    RewriteCond %{REQUEST_METHOD} !=POST
    RewriteCond %{QUERY_STRING} =""
    RewriteCond %{REQUEST_URI} \/$
    RewriteCond %{HTTP_COOKIE} !(comment_author|wp\-postpass|w3tc_logged_out|wordpress_logged_in|wptouch_switch_toggle) [NC]
    RewriteCond "%{DOCUMENT_ROOT}/wp-content/cache/page_enhanced/%{HTTP_HOST}/%{REQUEST_URI}/_index%{ENV:W3TC_PREVIEW}.html%{ENV:W3TC_ENC}" -f
    RewriteRule .* "/wp-content/cache/page_enhanced/%{HTTP_HOST}/%{REQUEST_URI}/_index%{ENV:W3TC_PREVIEW}.html%{ENV:W3TC_ENC}" [L]

</IfModule>
# END W3TC Page Cache core
```

If i set a list of ignorable parameters like `utm_source`, `utm_medium`, `utm_term`, `utm_content`, `utm_campaign` and `gcli` (google analitycs/adwords), w3tc doesn't ignore the parameters and not use the cache.

My idea is remove "ignorable parameters" via htaccess:

```
# BEGIN W3TC Page Cache core
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

# copy QUERY_STRING in env var
RewriteRule ^ - [E=CustomQueryString:%{QUERY_STRING}]

# delete utm_source param
RewriteCond %{ENV:CustomQueryString} ^(.*)&?utm_source=[^&]+&?(.*)$ [NC]
RewriteRule ^ - [E=CustomQueryString:%1%2]

# delete utm_medium param
RewriteCond %{ENV:CustomQueryString} ^(.*)&?utm_medium=[^&]+&?(.*)$ [NC]
RewriteRule ^ - [E=CustomQueryString:%1%2]

# delete utm_term param
RewriteCond %{ENV:CustomQueryString} ^(.*)&?utm_term=[^&]+&?(.*)$ [NC]
RewriteRule ^ - [E=CustomQueryString:%1%2]

# delete utm_content param
RewriteCond %{ENV:CustomQueryString} ^(.*)&?utm_content=[^&]+&?(.*)$ [NC]
RewriteRule ^ - [E=CustomQueryString:%1%2]

# delete utm_campaign param
RewriteCond %{ENV:CustomQueryString} ^(.*)&?utm_campaign=[^&]+&?(.*)$ [NC]
RewriteRule ^ - [E=CustomQueryString:%1%2]

# delete gclid param
RewriteCond %{ENV:CustomQueryString} ^(.*)&?gclid=[^&]+&?(.*)$ [NC]
RewriteRule ^ - [E=CustomQueryString:%1%2]

# if %{ENV:CustomQueryString} is empty cached pare are served
RewriteCond %{HTTP:Accept-Encoding} gzip
RewriteRule .* - [E=W3TC_ENC:_gzip]
RewriteCond %{HTTP_COOKIE} w3tc_preview [NC]
RewriteRule .* - [E=W3TC_PREVIEW:_preview]

RewriteCond %{REQUEST_METHOD} !=POST
RewriteCond %{ENV:CustomQueryString} =""
RewriteCond %{REQUEST_URI} \/$
RewriteCond %{HTTP_COOKIE} !(comment_author|wp\-postpass|w3tc_logged_out|wordpress_logged_in|wptouch_switch_toggle) [NC]
RewriteCond "%{DOCUMENT_ROOT}/wp-content/cache/page_enhanced/%{HTTP_HOST}/%{REQUEST_URI}/_index%{ENV:W3TC_PREVIEW}.html%{ENV:W3TC_ENC}" -f
RewriteRule .* "/wp-content/cache/page_enhanced/%{HTTP_HOST}/%{REQUEST_URI}/_index%{ENV:W3TC_PREVIEW}.html%{ENV:W3TC_ENC}" [L]

</IfModule>
# END W3TC Page Cache core
```

my proposal is https://github.com/szepeviktor/w3-total-cache-fixed/pull/223

please help me to test it before merge the PR.

**Comment by amiga-500** [comment]
Interesting feature.  I always thought those parameters (e.g. utm_medium, utm_term, utm_content, utm_campaign) were only passed back as cookies after visiting a url.  Didn't know they are queries.

Out of curiosity...so would one case be:  a google ad from adwords is clicked which then takes the user to the site but that url contains one or more of those query variables?  Is that how this case happens?  And because if it does the page will not serve a cache.  I assume the query string is only passed in the first place so as to be picked up by the google analytics javascript embeded in the page?

Thanks

**Comment by nigrosimone** [comment]
Yep

when you click on adwords ads it pass a [gclid param](https://www.wordstream.com/gclid) in the query. 

 utm_* parameters are used for make [custom campain](https://support.google.com/analytics/answer/1033867?hl=en).

>  I assume the query string is only passed in the first place so as to be picked up by the google analytics javascript embeded in the page?

yep, all params are passed on the first request, after first request, google set all info into cookie

**Comment by amiga-500** [comment]
Very cool!  It'll be a pleasure to test this and the preload feature later today.  Much appreciated for the awesome work!

**Comment by amiga-500** [comment]
Oh i need to point out one important thing:

Technically w3tc **_did_** serve up a cached page when there were entries under the "_Accepted Query Strings_" field before your new PR, but it only did its check internally (after making its way through _advanced_cached.php_) and then it finds the query matches and then serves up what is found on disk (the cached page).  So even though it is in Disk Enhanced it still needed to access the plugin and find the query match before serving the cache page....so for queries it is acting like Disk Basic when serving caches even though its using Disk Enhanced mode.  This only occurred for query string requests.

But with your PR, its shifting this query check from being done internally to now doing this similarcheck inside .htaccess instead.  

So I am curious...which is preferred?  It would technically be more efficient if done in htaccess because it doesnt have to call w3tc to do its internal checks.

**Comment by amiga-500** [comment]
And lastly, there is a slight difference in what is done internally and what is being done in your PR....

The internal code version that handles "_Accepted Query Strings_" field (as mentioned in my last reply) assumes that if a matching query is present in a url then the url should be cached (or a cache is to be served), regardless of what other (non-matching) query variables are present.

For example:

_Accepted Query Strings_: **foo=bar**

```
WILL CACHE PAGE: http://www.domain.com/?var1=1&foo=bar&var2=2&var3=3
```
In your PR it has a distinct difference.  It says, if there is a query in the url that doesn't match (after stripping the ones that did match), then the page should not cache.

For example:

_Accepted Query Strings_: **foo=bar**

```
DON'T CACHE: http://www.domain.com/?var1=1&foo=bar&var2=2&var3=3
```
So prior to your PR, w3tc would serve a cache page for `http://www.domain.com?var1=1&utm_source=test` because `utm_source` was a match despite a `var1=1` also being present.

So it depends on what we want it to be:

* Only cache the page if 1 or more of the _Accepted Query Strings_ exists.  However, if there are non-matching queries variables also present in the URL then cache anyway.  _This is what it currently does prior to your PR_

**OR**

* Only cache the page when 1 or more of the _Accepted Query Strings_ exists.  However, if there are non-matching query variables also present in the URL then do not cache the page.  _This is what your PR does._

**Comment by nigrosimone** [comment]
> So I am curious...which is preferred? It would technically be more efficient if done in htaccess because it doesnt have to call w3tc to do its internal checks.

I didn't know this features (fallback on disk basic)... disk enhanced is better, more efficient.... but

> there is a slight difference in what is done internally and what is being done in your PR.... [..] if a matching query is present in a url then the url should be cached (or a cache is to be served)

mmmh... it's no good! wordpress/plugins have some query parameters that totally change the content eg: pagination, language, filters, see this example:

http://www.domain.com/?p=2&lang=fr&utm_sources=ads&utm_medium=banner120x90

parameters like "utm_sources" and "utm_medium" no change the content, are only for analitycs tracking, on the contrary parameters like "p" (wordpress pagination) and "lang" (language selection by wpml) totally change the page content.

i think the better solution is: 

> Only cache the page when 1 or more of the Accepted Query Strings exists. However, if there are non-matching query variables also present in the URL then do not cache the page.

because i know what parameters w3tc can ignore, but not know all possible use/combination/context


Thanks Kimberly!
without you this project would die ;)

**Comment by amiga-500** [comment]
> _parameters like "utm_sources" and "utm_medium" no change the content, are only for analitycs trackin, on the contrary parameters like "p" (wordpress pagination) and "lang" (language selection by wpml) totally change the page content._
> _because i know what parameters w3tc can ignore, but not know all possible use/combination/context_

I totally agree with you!  I'll just make some extra checks and final adjustmen and we should be good to go.

**Comment by amiga-500** [comment]
Done.
