### ISSUE TITLE
[0.9.4.x] AuthorizationHeaderMalformed

### ISSUE THREAD

**Issue by PietsHost** [szepeviktor/fix-w3tc#236]
> Error: Unable to put object (S3::putObject(): [AuthorizationHeaderMalformed] The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1').

**Comment by amiga-500** [comment]
Hi @PietsHost ..... 

1. Are u using the v0.9.4.x generation build or v0.9.5.x build (we try to do fixes for both gens)?
2. And can you walk me through how you generated that error message?  I will make it a priority to fix.

Thanks
Kimberly.

**Comment by amiga-500** [comment]
Hi @PietsHost 

Did you set your _Bucket Region_ correctly  (located under: _Performance > CDN > Configuration_) since by default it is set to "us-east-1"  (aka _US East (N. Virginia)_).  In your case your bucket should be set to _**EU (Frankfurt)**_ (which is the _eu-central-1_) -- see image below.

![bucket](https://cloud.githubusercontent.com/assets/5191497/21597339/8070fd36-d117-11e6-99fa-931efa54e882.gif)

**Comment by PietsHost** [comment]
I'm sorry but there is no such drop down menu...
![img_0686](https://cloud.githubusercontent.com/assets/3725416/21597441/2aac03da-d14b-11e6-9b62-b0aab3c2b91b.PNG)
![img_0687](https://cloud.githubusercontent.com/assets/3725416/21597442/2acec546-d14b-11e6-9d5e-73c7ca227526.PNG)

**Comment by amiga-500** [comment]
Ahh i see the problem.  Sorry about that.  It seems i forgot to put the missing field for "CloudFront" users.  The field only appears when you are using  "Amazon Simple Storage Service (S3)" as the CDN (under _General Settings > CDN > CDN Type_) but because CloudFront also uses S3 i forgot to add the region selector box to it too.  It's a simple fix.  I will do that today and provide you the direct file(s) you need to update on your site.

Once again, my apologies for my oversight.

Cheers
Kimberly

**Comment by amiga-500** [comment]
@PietsHost, 

Ahh i see the problem.  Sorry about that.  It seems i forgot to put the missing field for "CloudFront" users.  The field only appears when you are using  "Amazon Simple Storage Service (S3)" as the CDN (under _General Settings > CDN > CDN Type_) but because CloudFront also uses S3 i forgot to add the region selector box to it too.  It's a simple fix.  I will do that today and provide you the direct file(s) you need to update on your site.

Once again, my apologies for my oversight.

If time is critical and you need a quick update right now just let me know and i can give you a step-by-step to make a quick modify to a file that will default your s3 bucket to _eu-central-1_ and then later today i will provide you with the official update.

Cheers
Kimberly

**Comment by PietsHost** [comment]
Thank you very much for this information.
I'll wait for the "official fix" ;-)

**Comment by amiga-500** [comment]
Hi again @PietsHost . Fixed it.  For your convenience, here are the updated files you need to replace on your end which will fix your problem (see below).  I haven't put this into a release yet -- and a new release won't be coming for a bit -- so it'll probably be in your best interest to grab these new files.  Anyway, once you've updated your files then just go over to _Performance > CDN > Configuration_ and change your Bucket region from _US East (N. Virginia)_ to _EU (Frankfurt)_.

[inc/options/cdn/cf.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/inc/options/cdn/cf.php)
[lib/S3.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/lib/S3.php)
[lib/W3/Cdn/S3.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/lib/W3/Cdn/S3.php)
[lib/W3/Cdn/S3/Cf.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/lib/W3/Cdn/S3/Cf.php)
[lib/W3/ConfigKeys.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/lib/W3/ConfigKeys.php)
[lib/W3/Plugin/CdnCommon.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/lib/W3/Plugin/CdnCommon.php)
[pub/js/options.js](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/87f6eaa5a483bc95712a58cf07cede17f71e03fc/pub/js/options.js)

Please let me know how it goes.

Cheers
Kimberly

**Comment by PietsHost** [comment]
Hi @amiga-500 , I uploaded all the files you provided.

Now i get the following error: "Error: Empty bucket region"

**Comment by amiga-500** [comment]
It sounds like the new _options.js_ file isn't being loaded (your browser is prolly still using a cached version of your old one).  Try this:

Open options.js from your browser: _http://**<your-domain.com>**/wp-content/plugins/w3-total-cache-fixed/pub/js/options.js?ver=0.9.4.6_

And search for the following section. The key part of interest shown is the line: `config[bucket_location]': jQuery('#cdn_cf_bucket_location').val()`.  In the file that line should actually appear twice (one in this section below and another time in a different section).

  If it does then attempt the "Test" again:
```javascript
 case 'cf':
    jQuery.extend(params, {
        engine: 'cf',
        'config[key]': jQuery('#cdn_cf_key').val(),
        'config[secret]': jQuery('#cdn_cf_secret').val(),
        'config[bucket]': jQuery('#cdn_cf_bucket').val(),
        'config[bucket_location]': jQuery('#cdn_cf_bucket_location').val(),
        'config[id]': jQuery('#cdn_cf_id').val()
    });
```


Thanks for the info
Kimberly

**Comment by amiga-500** [comment]
Hi @PietsHost ...

It sounds like the new _options.js_ file isn't being loaded (your browser is prolly still using a cached version of your old one).  Try this:

Open options.js from your browser: 

_`http://<your-domain.com>/wp-content/plugins/w3-total-cache-fixed/pub/js/options.js`_ 

I, of course, am assuming you aren't caching/minifying your admin pages and this options.js file is being loaded directly when u visit the w3tc pages.

And search for the following section. The key part of interest shown is the line: `config[bucket_location]': jQuery('#cdn_cf_bucket_location').val()`.  In the file that line should actually appear twice (one in this section below and another time in a different section).  If it does then attempt the "Test" again (since it could now be refreshed).

```javascript
 case 'cf':
    jQuery.extend(params, {
        engine: 'cf',
        'config[key]': jQuery('#cdn_cf_key').val(),
        'config[secret]': jQuery('#cdn_cf_secret').val(),
        'config[bucket]': jQuery('#cdn_cf_bucket').val(),
        'config[bucket_location]': jQuery('#cdn_cf_bucket_location').val(),
        'config[id]': jQuery('#cdn_cf_id').val()
    });
```

Thanks for the info
Kimberly
