### ISSUE TITLE
[0.9.5.x] Update CSSTidy

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#278]
@amiga-500 same for php7, CSSTidy can be updated by copy/paste!

**Comment by amiga-500** [comment]
Sure.  Happy to do it.  There are some other modifications that will need to be done though since it involved more than a copy/paste -- it required modifying an additional 12 w3tc files outside csstidy just to get the new version of csstidy to function fully.  I will  sniff around 095x to find those equivalent 12 files and the corresponding locations and then stitch them in.

**Comment by nigrosimone** [comment]
closed by https://github.com/szepeviktor/w3-total-cache-fixed/issues/196#issuecomment-272685689

waits for next official release.

**Comment by nigrosimone** [comment]
Reopen.... latest release has old csstidy.

**Comment by amiga-500** [comment]
**Done** (PR #317)
