### ISSUE TITLE
CDN Generic Mirror doesn't work with "{uploads_dir}/*" in "Custom file list"

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#296]
From official support forum https://wordpress.org/support/topic/w3tc-0-9-5-2-break-cdn-when-using-generic-mirror/

On 0.9.5.2 with "Generic Mirror" CDN, if user add in the "Custom file list" the rule "{uploads_dir}/*" the front-end will be totally broken.

**Steps to reproduce:**
1) Enable CDN and set on "Generic Mirror"
2) In CDN settings page, in "Replace site's hostname with" set a mirror host eg.: cdn.wordpress.local 
3) In CDN settings page, in "Custom file list" add: {uploads_dir}/*
4) Save the settings

Now the front-end is totally break, because the method `replace_all_links` in the class `_Cdn_Plugin_ContentFilter` in the file `Cdn_Plugin.php` replace in the wrong way the links. The final output is eg.:
```html
<html class=http://cdn.wordpress.local/"http://cdn.wordpress.local/"http://cdn.wordpress.local/lang="http://cdn.wordpress.local/it-IT"http://cdn.wordpress.local/prefix="http://cdn.wordpress.local/og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#"http://cdn.wordpress.local/>
....
....
```

**Comment by szepeviktor** [comment]
Could you open a PR?

**Comment by nigrosimone** [comment]
I don't have a fix :(

**Comment by amiga-500** [comment]
Hi guys.  Just watching tv and figured i'd have a stab at this.

I believe the problem is that the `{uploads_dir}` placeholder when converted is becoming a full url instead of being just its path like `{wp_content_dir}` and `{plugins_dir}` is done via `Util_Environment::url_to_uri()` in _Cdn_Util.php_ (line 233).  So to resolve the `{uploads_dir}/*` problem it would require changing:
```php
$uploads_uri = $upload_dir['baseurl'];
```
to
```php
$uploads_uri = Util_Environment::url_to_uri($upload_dir['baseurl']);
```
I tested it out and it fixed the problem.  However, since the `{uploads_dir}` can be modified in WP to be a different domain maybe this isnt a good idea. 

That is when i discovered something else.  Although the above fixes the problem with `{uploads_dir}/*` i notice that if anyone were to use a full url (e.g. http://foo.bar/pics/*) in the Custom Files list box it appears that could cause problems.  And again, that is also why when `{uploads_dir}` was used it totally breaks the front-end.

 In _Cdn_Plugin.php_ within the `fill_regexps()` function on line 1025 is the regex that handles full urls  placed in the Custom Files list.  The problem with it is that the regex doesnt seem to be complete.  If anyone were to give a full url in the Custom file lists text box (in this case, `{uploads_dir}` was doing just that) it would  cause a mess in the page which is what we saw.  The mess is primarily due to the "**?**" in the regex found on line 1025.  Removing it would stop the mess but it would replace the entire url with just the cdn host name in the page -- losing the url path.  So it seems this regex needs to be revised.

So that being said, it seems you should skip modifying the _Cdn_Util.php_ fix i mentioned above entirely and just fix handling full urls correctly.  Doing so would not only fix the `{uploads_dir}/*` issue but would also handle other full urls:

So the fix could be:

Line 1009-1010:
```php
if ( Util_Environment::is_url( $mask ) ) {
    $custom_regexps_urls[] = Cdn_Util::get_regexp_by_mask( $mask );
```
is changed to:
```php
if ( Util_Environment::is_url( $mask ) ) {
    $parse_url = @parse_url( $mask );
    if ( $parse_url && isset( $parse_url['host'] ) ) {
        $mask = $parse_url["path"];			
	$domain_url = Util_Environment::get_url_regexp( sprintf( '%s://%s%s', ( isset( $parse_url['scheme'] ) ? $parse_url['scheme']:'' ), $parse_url['host'], ( isset( $parse_url['port'] ) && $parse_url['port'] != 80 ? ':' . (int) $parse_url['port'] : '' ) ) );
	$custom_regexps_urls[] = array('domain' => $domain_url, 'path' => Cdn_Util::get_regexp_by_mask( $mask ));
    }
```
and Line 1025:
```php
$regexps[] = '~(["\'(=])\s*((' . $regexp . ')?(()([^"\'() >]*)))~i';
```
is changed to:
```php
$regexps[] = '~(["\'(=])\s*((' . $regexp['domain'] .')?((' . $regexp['path'] . ')([^"\'() >]*)))~i';
```

I tried it and it seems to work.  Feel free to give it a go by using this PR #314 and let me know if it works for you and/or if you have other questions/input.

Back to watching tv for me -- the American's inauguration thing is on every channel here in Canada...go figure.

Cheers
Kimberly :octocat:
