### ISSUE TITLE
Gzipped cached pages are not decoded

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#312]
From the support forum, many user has a issue with gzip and cached page.

the issue appears when..
- browser cache is enabled
- gzip under browser cache is enabled
- the page is cached
- the user is not log on

the issue disappears when..
 - disable GZip under Browser Cache seems to solve the issue

the page on website appears:
![alt text](https://pbs.twimg.com/media/C2e9quQWIAAEPiV.jpg)

some topic:
https://wordpress.org/support/topic/white-homescreen-after-latest-update/
https://wordpress.org/support/topic/w3tc-causes-garbled-code-display-on-pages/

**Comment by szepeviktor** [comment]
> disable GZip under Browser Cache seems to solve the issue

Disabling GZip under Browser Cache seems to be **a word-around**

**Comment by szepeviktor** [comment]
This .htaccess content makes a gzipped html file work
```apache
AddType text/html .html_gzip
AddEncoding gzip .html_gzip

SetEnvIfNoCase Request_URI \.html_gzip$ no-gzip
```

**Comment by szepeviktor** [comment]
Or the page could be double-gzipped...

**Comment by nigrosimone** [comment]
do you know how replicate the issue?

**Comment by szepeviktor** [comment]
No, I am an official w3tc-only user.

**Comment by szepeviktor** [comment]
> do you know how replicate the issue?

Maybe by removing the above rules.

**Comment by amiga-500** [comment]
I was playing around and found the problem can only be replicated if you change your php version to 5.3.x (i didn't try lower versions though).  Anything from v5.4 and up will not experience this problem.  

Didn't WP or W3TC have a minimum PHP version requirement?  I thought one (or both?) of them was v5.4.  I can't remember.  It's been a while. 😺 

Anyway, i am heading out for the day so i wont be able to tackle this and its connection to 5.3.x for a while but i just wanted to give you guys some new insight.

Cheers
Kimberly :octocat:

**Comment by szepeviktor** [comment]
😢 5.2.4 https://wordpress.org/about/requirements/

**Comment by szepeviktor** [comment]
Spotted something:

http://php.net/manual/en/function.gzdeflate.php

> 5.4.0 	Added encoding parameter.

**Comment by szepeviktor** [comment]
And w3tc includes that parameter in lib/Minify/HTTP/Encoder.php:254
`gzdeflate($this->_content, $compressionLevel);`

Maybe I am wrong.

**Comment by nigrosimone** [comment]
From doc http://php.net/manual/en/function.gzdeflate.php

> Version.  Description
> 5.4.0.      Added encoding parameter.

**Comment by amiga-500** [comment]
I found the specific area causing the problem. It's in _PgCache_ContentGrabbber.php_ line 1244-1246. 

```php 
if ( isset( $value0['n'] ) ) {
    $name = $value0['n'];
    $value = $value0['v'];
}
```
Just working my way backwards to figure out why this was needed.  So to solve the problem (for php5.3 users) these lines either have to be stripped or modified.  Of course i am speaking too early since i dont know what they do just yet.  Right now they send back garbage headers to the client browser:

```
F: F, F
p: p
m: m
g: g
A: A
```

**Comment by nigrosimone** [comment]
Great catch! the fix is a simple php version check er in lib/Minify/HTTP/Encoder.php:254,  eg.:
```php
if (version_compare(phpversion(), '5.4.0', '<')) {
   gzdeflate($this->_content);
} else {
    gzdeflate($this->_content, $compressionLevel);
}
```
I'm right?

**Comment by amiga-500** [comment]
Ahh i will check it out.

**Comment by amiga-500** [comment]
Ok i checked.  nope the problem is still there.  I believe because gzdeflate's 3rd parameter is what was introduced in 5.4 (aka _`[, int $encoding = ZLIB_ENCODING_RAW ]]`_)  Since w3tc only uses the 1st two parameters it should work fine in pre-5.4.  If i am understanding it wrong please correct me.

Ok, back to my potential clue.

**Comment by nigrosimone** [comment]
You are right.

**Comment by nigrosimone** [comment]
> I found the specific area causing the problem. [...]

But removing those lines it works?

**Comment by amiga-500** [comment]
Yup when those lines are removed then things start working again -- all versions of php start working as expected.

**Comment by nigrosimone** [comment]
Mhh,  ok but those line are important?

**Comment by amiga-500** [comment]
Still roaming the code and yea these lines are necessary when one makes use of the _w3tc_repeating_headers_ filter **and** have the same header name in the cache headers input box.  

From what i see these lines are used to allow for repeating headers to send back to the user e.g. "set-cookie".  But is used only when the user implements the filter and adds it into the cache headers input box.   So it's pretty rare that someone will make use of this feature.

So far w3tc's code looks correct and the problem lies in how php 5.3 is doing things.  php 5.3 is seeing an array that doesnt exist (w3tc didnt add it).  So i dont think its a bug in w3tc but either a bug in php 5.3 or how it interprets things.

I will go play with php 5.3 and their array handling and get back to ya what i learn

**Comment by amiga-500** [comment]
Ok i got it fixed :bowtie:

To fix the problem you need to change line 1244 (of _PgCache_ContentGrabbber.php_) from:

```php
if ( isset( $value0['n'] ) ) {
```
to this:

```php
if ( is_array($value0) && isset( $value0['n'] ) ) {
```
Notice the only change is the inclusion of _**`is_array($value0) &&`**_

What is happening is php 5.3's `isset()` function interprets the parameter given (ie, `$value0['n']`) as a string of characters not a placeholder for an array and so the `isset()` ends up being TRUE.  And the index value of `'n'` ends up being index 0 into this string.  What that does is it returns the first letter of the header's value back to the user e.g. _"Cache-Control: max-age=3600, public"_ becomes _"m: m"_.  This peculiar behavior doesn't affect php 5.4 and onward.

If you want to see the problem in action i can give you test code to play at PHP Sandbox site (the site allows u to set the php version to anything you want).

Kimberly :octocat: 

PR #313

**Comment by amiga-500** [comment]
If there are no objections after discussion i will do a PR

**Comment by nigrosimone** [comment]
Great work @amiga-500! It's ok for me!
