### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach -> ConfigCompatibility.php

### ISSUE THREAD

**Issue by joshin42** [szepeviktor/fix-w3tc#35]
Hey all,

Thanks for cleaning up and fixing W3TC. I appreciate all your work on this!

I'm seeing this warning:

PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/www/sitename.com/htdocs/wp-content/plugins/w3-total-cache/lib/W3/ConfigCompatibility.php on line 207, referer: http://www.sitename.com/wp-admin/

This is on a fresh pull ( e2ae84e).

Thanks!

Edited to add: PHP 7.0.6

**Comment by nigrosimone** [comment]
you have downloaded the master?

**Comment by joshin42** [comment]
Yes. I did it about an hour before I posted here.  (And yes, I did clear all caches W3TC, Apache, and php-fpm.)

I've logged out of the dashboard & back in, and now can't replicate the error. Even with deactivating and reactivating the plugin.

Consider it an anomaly until I get it to recur. 

Thanks!

**Comment by charlesLF** [comment]
Hey @joshin42,

Thanks for reporting this! I was able to replicate the warning message by doing the following:

1. Start with a fresh WP installation
2. Install W3TC from the WP repo
3. delete the w3-total-cache folder
4. clone the github fork (e2ae84e) into a new w3-total-cache folder

The problem is from a missing file in this repo, namely `configs/0.9.4.1-ConfigKeys.php`

Upon the first run (after an upgrade) w3tc tries to check for changes in the default settings between the older version and the newer one. It does so by using the ConfigKeys in the configs folder.
The latest w3tc version (on the WP repo) is 0.9.4.1, so the plugin tries to read from  `configs/0.9.4.1-ConfigKeys.php`, which does not exist, and so the error message is thrown.

I will create a pull request to fix this.

**Comment by nigrosimone** [comment]
my mistake. sorry guys.

**Comment by joshin42** [comment]
Thanks nigrosimone & charlesLF!

Glad on this at least that I wasn't insane. :)
