### ISSUE TITLE
Garbage collector issues

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#359]
From  latest update on official support forum i have read some issue with garbage collector, it seems always purge all the cache each time it run:

https://wordpress.org/support/topic/strange-cache-updates-page-enhanced-html-old/
https://wordpress.org/support/topic/page-expiry-cant-seem-to-change-it-from-1-hour/

On my dev site the cache expiring is set on 1 day
http://sndsgn.altervista.org/test-cache/
But the cache seem purged every time cron run (each minutes)

I don't investigate my self because far to my home.

**Comment by amiga-500** [comment]
Hi @nigrosimone!  Sounds like a fascinating problem to tackle.  Oddly i can't seem to generate the same problem on my side.  It works perfectly.

Why is it you guys can always get the fun disasters to happen so easily and i cant :stuck_out_tongue_winking_eye:

So the facts are:

* It's specific to _Disk:Enhanced_ mode
* You have your Browser Cache's _HTML Expires Header Lifetime_ set to **86400** seconds (1 day)
* Your _Automatic Priming the Cache_ is disabled

What is your Page Cache's _Garbage Collection Interval_ set to?  Is it 300 seconds (5 minutes)?  Just trying to see if there is a direct correlation with the GC or if it is ignoring the GC interval, which will point to something more buried.

How is your wp cron set up?  Are you using the default way where wp-cron simply runs when visitors hit the site or did you disable that and having a real cron job run every xx minutes (to hit wp's doing_wp_cron script).

I wonder if the **`filemtime()`** function in _Cache_File_Cleaner_Generic.php_ is returning back false because of a lack of permissions or something (e.g. the admin has blocked certain php commands from running).  If that happens then when the Garbage Collector runs it will kill all pages (set them to ".old") on a site.

Thanks for the info
:octocat: 

PS -

Can you run this script on your site just to verify that both `filemtime()` and `file_exists()` are allowed to be used and that the `time()` that is returned matches the current GMT time?:

```php
<?php

echo "<i>filemtime()</i> is <b>". ( cmd_enabled( 'filemtime' ) ? "AVAILABLE" : "NOT Available" ) . "</b><br />";
echo "<i>file_exists()</i> is <b>". ( cmd_enabled( 'file_exists' ) ? "AVAILABLE" : "NOT Available" ) . "</b><br />";

date_default_timezone_set( 'UTC' );
echo "Current GMT time is: <b>" .date( "M d Y h:i:s" ) . "</b> should match what is shown at: <a href='https://greenwichmeantime.com/'>https://greenwichmeantime.com/</a>";

function cmd_enabled( $cmd ) {
    $disabled = explode( ',', ini_get( 'disable_functions' ) );
    return !in_array( $cmd, $disabled );
}

```

**Comment by nigrosimone** [comment]
> Can you run this script on your site 

http://sndsgn.altervista.org/info.php

>  that is returned matches the current GMT time?

Server time: 03:27:50
Local time: 4:30:14 PM

**Comment by nigrosimone** [comment]
- Disk:Enhanced mode
- Browser Cache's HTML Expires Header Lifetime set to 86400 seconds (1 day)
- Priming the Cache is enabled
- Page Cache's Garbage Collection Interval is set to 300 
- i have both.. the real cron job run every 1 minutes by with http request on /wp-cron.php

**Comment by nigrosimone** [comment]
> filemtime() function in Cache_File_Cleaner_Generic.php is returning back false because of a lack of permissions or something

On cheap / free hosting can return false by  too many reading operation on disk

**Comment by amiga-500** [comment]
Thanks for the values.  I now have the exact same settings and still no luck (everything still works) :(  ... i will set up an account with altervista.org like you did and do tests there instead.

**Comment by nigrosimone** [comment]
No kimberly don't waste your time... my issue seems not correlate to garbage collector. In my case latest w3tc not caching nothing, in the htnl i see "request uri is rejected",  but this is another issue. 

Always thanks!
