### ISSUE TITLE
Missing 0.9.4.x features in the 0.9.5.x

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#373]
Just a to-do list of 0.9.4.x's missing feature in the 0.9.5.x branch:
1. [x] [~Query String Update~](https://github.com/szepeviktor/w3-total-cache-fixed/pull/229)
2. [x] [~New filter: _w3tc_pgcache_lifetime~](https://github.com/szepeviktor/w3-total-cache-fixed/pull/74)
3. [x] [~Expanded Regular Expression Support~](https://github.com/szepeviktor/w3-total-cache-fixed/pull/69)
4. [x] [~Smart Browser Cache Defaults~](https://github.com/szepeviktor/w3-total-cache-fixed/pull/64)
5. [x] [~Feeds Not Caching & Not Serving Back as XML~](https://github.com/szepeviktor/w3-total-cache-fixed/pull/85)
6. [x] [~Deprecated the "Allow, Deny, and Order" directives~](https://github.com/szepeviktor/w3-total-cache-fixed/pull/418)

I have checked all 0.9.4.x PRs... have i missed someone? E.g. [List of our features not included in 0.9.5](https://github.com/szepeviktor/w3-total-cache-fixed/issues/116#issuecomment-250105738)

**Comment by amiga-500** [comment]
Hi @nigrosimone .. I updated the list.  Those are the remaining ones. 

However, i did not include into the list the "_**Embed Content Instead of Using External File(s)**_" feature for both JavaScript and CSS that is in v0.9.4.x but not in v0.9.5.x.

I didn't add it above because i see Frederick has a similar feature under _Minify_ (for CSS only) called: "_**Eliminate render-blocking CSS by moving it to HTML body (Available after upgrade)**_" which is disabled because as you can read, it requires one to upgrade :moneybag: 

So, this indicates to me if i were to port over the v0.9.4.x feature (it embeds for both CSS and JavaScript) to v0.9.5.x it will be rejected immediately by Frederick because he wants people to upgrade to have access to that feature :(

If you think i should still add the feature -- since it does more (it does JavaScript too) --  just let me know.

Thanks
Kimberly

**Comment by nigrosimone** [comment]
> So, this indicates to me if i were to port over the v0.9.4.x feature (it embeds for both CSS and JavaScript) to v0.9.5.x it will be rejected immediately by Frederick because he wants people to upgrade to have access to that feature :(

you are totally right... don't waste your time, otherwise on each Frederik's updates we lose this feature and you have to reimplement the features. For the 0.9.5.x the better idea is follow the Frederik's strategy. Also, if we made a "vital" feature over the official version and users rely the website's operability on this feature, if Frederik don't merge the feature into the official plugin, we risk to broken user's website.

**Comment by szepeviktor** [comment]
Almost done!  4/5

**Comment by szepeviktor** [comment]
> on each Frederik's updates we lose this feature

@ftownes If w3tc would be modular (hookable) we could implement/fix these in a separate plugin.

**Comment by nigrosimone** [comment]
[Deprecated the "Allow, Deny, and Order" directives](https://github.com/szepeviktor/w3-total-cache-fixed/pull/24)  (_old but gold_)

v0.9.5.x has missed https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/PgCache_Environment.php#L1192

**Comment by nigrosimone** [comment]
close https://github.com/szepeviktor/w3-total-cache-fixed/pull/418
