### ISSUE TITLE
Files paths in /plugin directory not rewritten to cloudfront URL

### ISSUE THREAD

**Issue by nolens** [szepeviktor/fix-w3tc#374]
Hello,

paths to /plugins folders are not rewritten to cloudfront CDN server URL unless I specify them in the "custom file list" input box, although I have already specified those file types in the "Theme file types to upload" dialogue:
`*.css;*.js;*.gif;*.png;*.jpg;*.ico;*.ttf;*.otf,*.woff,*.less`

In order to have those filetypes delivered by cloudfront, I have to enter this in "custom file type" input box:

```
{plugins_dir}/*.js
{plugins_dir}/*.css
{plugins_dir}/*.gif
{plugins_dir}/*.jpg
{plugins_dir}/*.png
```

I am experiencing this issue since many releases from the official wp repository, so this is not strictly related to your release. 

Thanks and regards,

Thomas

PS: I am a big fan of your plugin. Thanks for your continuing efforts!

**Comment by nigrosimone** [comment]
You have already checked if this fixs solve your problem?
[Rewrite URLs via wp_..._for_js() filter when CDN is Enabled](https://github.com/szepeviktor/w3-total-cache-fixed/pull/336)
[CDN Custom Files Issue with Full Urls](https://github.com/szepeviktor/w3-total-cache-fixed/pull/316)

**Comment by nolens** [comment]
Maybe I was not clear in my original description, so I have updated it:

> paths to /plugins folders are not rewritten to cloudfront CDN server URL unless I specify them in the "custom file list" input box, although I have already specified those file types in the "Theme file types to upload" dialogue....

Is that clearer? 

It is not a big issue, because URL rewriting works once these variables are set in the "custom files" input box. But it seems that rewriting the URLs to CDN path should work even without that workaround - don't you think?

**Comment by nigrosimone** [comment]
> don't you think?

yep, you are right.

**Comment by nigrosimone** [comment]
just an little update... surprise, surprise, the code is a bit confused... w3tc seems to build a wrong regular expression that not matching the full path in the right way... the fix require a bit of time... @amiga-500 has already fixed some others issue with cdn and rewriting logic and i/we need her help! :)

**Comment by amiga-500** [comment]
hi @nolens  ... can you clarify for me ... my mind is jumping around doing other things so i havent sat to put much thought into this just yet but you mention adding your file types under _Theme file types to upload_ but you follow by saying you arent getting your file types from the _{plugins_dir}_ to be CDN url rewritten.

Unless i've been wrong all this time the _{plugins_dir}_ is not the same as your theme directory. e.g.

Valid file selected examples when using _{plugins_dir}/*.png_ would be:
```
wp-content/plugins/w3-total-cache/pub/img/w3tc-sprite.png
wp-content/plugins/akismet/logo.png
```
Valid file selected examples when using the _*.png_ filter under _Theme File Types to Upload_ would be:
```
wp-content/themes/twenty-seventeen/screenshot.png
wp-content/themes/super-theme/images/search-button.png
```
So unless a _{plugin_dir}/*.png_ is listed in the _Custom File List_ box i wouldn't expect _w3tc-sprite.png_ or _logo.png_ (of my examples above) to be url rewritten nor uploaded, but i would expect _screenshot.png_ and _search-button.png_ to be.

**Comment by nolens** [comment]
Hi @amiga-500, 
yes, you are kind of right. I had a close look at the descriptive text of the input fields:

![screenshot](https://cloud.githubusercontent.com/assets/21305551/22864877/8f3f7f1a-f159-11e6-93c7-3ff6c2dc7704.png)

I just don't find it neither very intuitive nor user friendly to differentiate between "theme folder " and "other folders". 

Why this differentiation at all? As an "average Joe" user, I just want all those files being served by CDN. "Average Joe" won't even bother double checking wether all files are being picked up by CDN once the filetypes appear in the "theme files" field. 

So now I think, the behavior I described above may indeed be intended, but I don't think it's user friendly.
 
Why not entering the filetypes that should be served by CDN _once_, and if want exceptions, there is a different input field for those. In my opinion, that would be a much more user friendly way with much less risk causing hassle with the average user.

Don't you think?

**Comment by amiga-500** [comment]
Hi @nolens  you make a valid point!  I agree with you.  Most people don't realize their theme folder, plugins, uploads, etc are outside their theme (physically).  They just think that their theme contains all those things since a theme makes use of plugins, etc and so from the minds-eye of "average joe" user its a hierarchy where those other objects are held within said theme.  And so when uploading a theme (via the file types) it would seem to them to mean upload it all.

But then you have other users (non-average joe -- usually, coder, technician types) who are very much aware of the distinction and don't want the theme file types to indicate everything not inside the physical location of their theme directory.

For me, when i first started fixing bugs and adding features to the CDN section i actually thought the same as you.  I was confused for a bit why my other files weren't being uploaded.  And this is coming from someone who was already knee-deep in the low-level coding underbelly of w3tc and the wp directory structure. :stuck_out_tongue_winking_eye: 

At the very least, it's possible to keep everything the same but just provide more default file types in the custom file list to include things like the lines you mentioned above e.g. **{plugins_dir}/*.jpg**, **{plugins_dir}/*.css**,... and even **{uploads_dir}/*** and then allow the user to come in and tweak those as they see fit later.

I will have to discuss it with the other guys here since they may harbor a different opinion; a view that i didn't consider.

Cheers
Kimberly
