### ISSUE TITLE
Using Amazon CloudFront with Generic Mirror

### ISSUE THREAD

**Issue by CodeTune** [szepeviktor/fix-w3tc#381]
WordPress Version: 4.7.2
w3 Total Cache Version: 0.9.5.2

I am unable to use Amazon CloudFront CDN distribution with Generic Mirror (Origin Pull).

**Comment by amiga-500** [comment]
Curious..why aren't you using Origin Pull: Amazon CloudFront?  Why are you using Generic Mirror to communicate to Amazon CloudFront instead?

Also, what kind of error message are you getting?

Thanks for the info
Kimberly

**Comment by amiga-500** [comment]
Hi @CodeTune ... Curious..why aren't you using Origin Pull: Amazon CloudFront?  Why are you instead using Generic Mirror to communicate to Amazon CloudFront?  Ahh i just realized you probably do so because its just much quicker to set things up.

Also, what kind of error message are you getting?

Thanks for the info
Kimberly

**Comment by CodeTune** [comment]
Hi @amiga-500 ... I thought that is preferable and easier to configure. Anyway, I will test if it works with Origin Pull: Amazon CloudFront and let you know my observations.

EDIT: As for the error message, there is no error message. The website is a complete mess with URLs leading to the CSS files on the CDN broken.

**Comment by amiga-500** [comment]
I will play around with Generic Mirror to see and hopefully get the same problems you get.

**Comment by amiga-500** [comment]
Hi again @CodeTune ... you can chill.  I am playing with Generic Mirror now and if i find any problems i will let you know.  In the mean time when you said "unable to use"...were you getting an error message?

**Comment by CodeTune** [comment]
Like I mentioned in an earlier edited post, there is no error message. The website is a complete mess with URLs leading to the CSS files on the CDN broken.

**Comment by amiga-500** [comment]
Hi @CodeTune just an update.  Okay,  _Generic Mirror_ is working perfectly on my end -- no broken links. 

### Questions:

1. Did you give CloudFront time to allow your (newly created?) distribution status to be officially labelled as "_Deployed_"?
2. Have you tried our [latest w3tc fixed release](https://github.com/szepeviktor/w3-total-cache-fixed/releases)?

If so then it seems to be a configuration problem on your end and not related to w3tc since i am unable to duplicate your issue.

**Comment by CodeTune** [comment]
I'll try it out and update this thread. Thanks @amiga-500 !

**Comment by amiga-500** [comment]
Hi again @CodeTune ... i assume you got it working?

**Comment by CodeTune** [comment]
Yes, I am able to confirm .... Version 0.9.5.2.2 fixes this with Generic Mirror! Thanks, @amiga-500
