### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#397]
Hello @amiga-500 !

Would you welcome https://github.com/amiga-500/w3-total-cache-fixed ?

**Comment by nigrosimone** [comment]
+1 for @amiga-500, is the most active user in this project.

but what happen to the tons of links everywhere? github redirect all links?

**Comment by szepeviktor** [comment]
> github redirect all links?

We had a name change. Do you remember?

**Comment by amiga-500** [comment]
Sorry for the delay @szepeviktor .  I wanted to finish up things in this repo before catching up in this section.  I usually get distracted easily and jump on a tangent when i see something new.  :stuck_out_tongue_winking_eye: 

> _Would you welcome https://github.com/amiga-500/w3-total-cache-fixed ?_

Hey that's a nice offer.   But sadly, I am putting this project aside for a few months (starting right now) so I figure its best to stay with you until I get back into the flow of things down the road. :racehorse: 

> _github redirect all links?_
> _**We had a name change. Do you remember?**_

Yup, if it were switched all links should redirect correctly.  Of course, hardcoded links should ideally be manually modified over time to point to the new area (e.g., v094x's updater links) since there is no point having them go through 301 redirects each time.

Prior to leaving i wanted to get in the remaining new bug fixes and push out new releases for v0.9.5.x and v0.9.4.x which i've now done.  For v0.9.5.x we now have [30+ bug fixes/new features/updates](https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog) after just a month since the official v0.9.5.2 release :tada: 

It's been really fun working with you, @nigrosimone, @charlesLF,  twiginteractive, thebeline, and the others.

Because this place can be an addictive distraction i've actually disabled my alerts just now so i don't feel compelled to jump back in while doing my medical work.

The wiki page (and front page) has been updated with all of our changes up to this point so Frederick (and other visitors) can see.  Frederick was previously made aware of this page by @nigrosimone.  Upon a new official release that wiki page should ideally be stripped of its list (assuming that all, or most, are now integrated into the next official release) and started all over again.

Talk to you all in the future,
Kimberly :octocat:

**Comment by szepeviktor** [comment]
Thank you.

**Comment by nigrosimone** [comment]
> I am putting this project aside for a few months [..] while doing my medical work

@amiga-500 this make me sad, i think your contribute in this project is absolutely important, without you will be hard have the same result. You have helped tons of users and fix tons of bug, but your real life is most important, always thanks for all and best wishes for your new job!!

i'm just a bit curious about your life, i think you are a very qualified developer, why you work in the medical instead of web/software house? :)

I hope to see you again, soon.

**Comment by wp-networks** [comment]
Thank you @amiga-500 for being so awesome; best of luck to you & hope to see you return to the project in future :)
