### ISSUE TITLE
Page Cache $key / Host Mismatch

### ISSUE THREAD

**Issue by stevesearer** [szepeviktor/fix-w3tc#41]
Hello,

I've been working with w3tc-fix on my local development environment and was having issues getting the cache to purge properly on when I would edit a post.

After a bit of debugging in `/lib/W3/PgCache.php` it appears that there was a mismatch between the $key and where the actual cache file was being saved due to my setup having a port number:

**$key**: `localhost:8888/contact/_index.html`
**Actual location**: `localhost/contact/_index.html`

So I made a few little edits to remove the port number and was able to get it working:

```
if ($request_uri){
     $is_ssl_request = ( strtolower(substr($request_uri, 0, 8)) == 'https://' );
     // $key = substr( $request_uri, $is_ssl_request ? 8 : 7 );

     // my additions begin
     $test_host = parse_url($request_uri, PHP_URL_HOST); 
     $test_path = parse_url($request_uri, PHP_URL_PATH);
     $test_key = $test_host . $test_path;
     $key = $test_key;
     // my additions end

} else {
     $key = $this->_request_host . $this->_request_uri;
}
```

Not sure if this would qualify as something worth submitting as it could somewhat of an edge case solution to my specific setup, but it seemed like it might be worth pointing out. Perhaps there is a more general purpose way to ensure the $key actually matches where the cache files are being saved.

Edit: and I know my code is not the best way of fixing this, but more of a little hacky thing to show the concept :)

Thank you,

**Comment by Volnus** [comment]
Huh interesting fix. There is value in it and I think it is worth testing on a live server for possible issues. @nigrosimone what do you think?

**Comment by rabin-io** [comment]
Using `parse_url` to parse the URI is much more robust then a simple hack with `substr`, i would call `parse_url` without any parameter and dose get all the elements of the URI to a single array, and use that, insted calling the function twice (once for each case host&path).

**Comment by charlesLF** [comment]
Nice catch, @stevesearer!
Thanks for pointing it out :+1: 

I tried it on my localhost and was able to replicate the issue using page cache (disk: enhanced).

The problem is indeed from the lines you identified.

I will outline here the reason behind this `$key` mismatch bug just for documentation purposes:

The function `_get_page_key()` can be called with or without the last parameter `$request_uri` .

The only time `$request_uri` is passed to the function is when `_flush_url()` is called from `PgCacheFlush.php`.

### Page Cache Get and Set
For the purposes of cache `get` and `set`, the `$request_uri` is never passed, which leads to the execution of the following line in `_get_page_key`
```php
$key = $this->_request_host . $this->_request_uri;
```
In this context, `$this->_request_host` and `$this->_request_uri` are defined in the class's `__construct()`` as:

```php
        $request_host = w3_get_host();
        $pos = strpos($request_host, ':');
        if ($pos !== false)
            $request_host = substr($request_host, 0, $pos);
        $this->_request_host = $request_host;

        $this->_request_uri = $_SERVER['REQUEST_URI'];

```
So, the `request_host` uses the hostname minus any port (via the substr).


### Page Cache Flush
Now, when it comes to the cache flush method, the `$request_uri` variable is passed as the full URL (including port).
This leads to the execution of the following line in `_get_page_key`:

```php
            $is_ssl_request = ( strtolower(substr($request_uri, 0, 8)) == 'https://' );
        $pos = strpos($request_host, ':');
        if ($pos !== false)
            $request_host = substr($request_host, 0, $pos);
            $key = substr( $request_uri, $is_ssl_request ? 8 : 7 );
```
You can see how the port is never stripped in `$request_uri`, unlike what's done in the class's `__construct()`.

### Solution
This has already been stated above, and very well outlined by @stevesearer.
I also think that the most robust way to remove the port number from `$request_uri` would be by using `parse_url`

**Comment by stevesearer** [comment]
Awesome, glad I could be of help. 

I'm having a similar issue on my live site which is `https://` where I believe the generated `$key` for the purpose of purging does not have `_ssl` appended as it ought to be from these lines:

```
/**
* Append encryption
*/
if ($encryption) {
     $key .= '_' . $encryption;
}
```

So using my example above, I believe a mismatch like the following is happening:

**$key**: `localhost/contact/_index.html`
**Actual location**: `localhost/contact/_index_ssl.html`

Not 100% certain and unfortunately I'm headed out of town and don't have time to test much out right now.

**Comment by charlesLF** [comment]
@stevesearer : Do you have "Cache SSL (https) requests" enabled in Performance => Page Cache?

**Comment by stevesearer** [comment]
@charlesLF Not currently as when I enable it I start getting Error 500s on the cached pages (the non-cached pages still work fine).

**Comment by charlesLF** [comment]
Interesting. That behavior (the 500 error) could merit opening a separate issue for tracking and fixing it.

From what I see, the `$encryption` variable is set to "ssl" in the flush function only when that option is enabled in the Page Cache settings, whereas the `_extract_cached_page` ignores the value of that option and just relies on the request URI itself.

I suggest we move that other bug to another issue so that we solve one thing at a time?

**Comment by stevesearer** [comment]
Sounds good, feel free to open a separate issue about it if warranted. Will check in over the next few weeks when I can to provide any input I can while I'm out of the office.

**Comment by nigrosimone** [comment]
@stevesearer, @Volnus, @rabin-io, @charlesLF  thanks for your time!

Someone has investigated if the same problem afflicts the database and objects cache  when the disk is chosen (it could also concern minified assets js and css)?

**Comment by charlesLF** [comment]
@nigrosimone, yeah it's rather the other way around. Disk cache isn't the problem.
The Page Cache module itself is the problem, regardless of what cache storage is used (memcached, Redis, disk, etc...)

**Comment by amiga-500** [comment]
I agree with many of you that `parse_url()` seems to be the best solution for this issue.

I figure the original lines in PgCache.php:
```php
$is_ssl_request = ( strtolower(substr($request_uri, 0, 8)) == 'https://' );
$key = substr( $request_uri, $is_ssl_request ? 8 : 7 );
```
could be replaced with something like this:
```php
$uri = parse_url($request_uri);
$key =  $uri["host"].
	    (isset($uri["path"])?$uri["path"]:"").
	    (isset($uri["query"])?"?".$uri["query"]:"");	   
```
btw @charlesLF  thanks for the detailed outline above.
