### ISSUE TITLE
Total Cache removes roles from $current_user

### ISSUE THREAD

**Issue by charlesLF** [szepeviktor/fix-w3tc#42]
User bhamrick from the W3TC support forum on wordpress.org reported the following bug:

> I’m trying to use the plugin Woocommerce CSV importer which enforces permissions by relying on the roles array on the $current_user object, as many other plugins do. W3 Total Cache is removing my ‘administrator’ role so $current_user->roles becomes an empty array. There are no actual DB changes, it just changes the value at runtime.
> 
> This looks to be an old bug, there’s a thread about the same issue from a year ago:
https://wordpress.org/support/topic/bug-w3tc-breaks-plugins-that-need-the-current-users-role/

I looked into it, and seems the bug has been there for more than a year.

The problem is with accessing the global variable `$current_user` and changing its fields when using `array_shift`.

A simple fix would be to replace `array_shift()` with `reset()` as mentioned in the linked thread above.

Taking it a step further, perhaps we should stop using the global variables altogether and get the `$current_user` by using:
```php
$current_user = wp_get_current_user();
```

Is there any argument for using the global variable instead of calling the function? Maybe an overhead cost in execution time?

**Comment by nigrosimone** [comment]
@charlesLF thanks for your time!

i think the best option change:

    global $current_user;

with:

    $current_user = wp_get_current_user();

everywhere...

![w3tc](https://s17.postimg.org/x9ztkw0u7/w3tc.jpg)

**Comment by charlesLF** [comment]
I agree.

I will prepare a pull request with the required changes.

**Comment by amiga-500** [comment]
Hi guys!  I always forget to check this "Issues" area ;P 

Great idea to use wp_get_current_user() since i get a sense the wp dev crew will eventually want all plugin/themes to use it and not its global equivalent.

Curious, @charlesLF  my coding knowledge is likely still rusty but if i am not mistaken by using: 

**`$current_user = wp_get_current_user();`**

The returned object will still directly reference back to the global class object and so its **roles** array member variable  will still get changed (globally) by **array_shift()**.  Correct me if i'm wrong.

So, if i'm right then the change might still need a slight tweak.  More specifically, the existing line:

**`$role = array_shift( $current_user->roles );`**

would need to be changed to something like: 

**`$role = array_values( $current_user->roles )[0];`**

in the following files:

**Line 936**: _lib/W3/Plugin/Cdn.php_
**Line 114**: _lib/W3/Plugin/NewRelic.php_
**Line 750**: _lib/W3/Plugin/TotalCache.php_

I decided not to use php's **reset()** because if other plugins/themes were to make use of the array pointer via functions like **next()** or **prev()** then an unexpected **reset()** by w3tc could possibly disturb there expectations.

Again, i could be wrong about needing this tweak so i wanted to discuss it here first. :)

**Comment by nigrosimone** [comment]
Have you time to made a PR?

**Comment by amiga-500** [comment]
Yup..happy to do it.  I will also do the same for the others.
