### ISSUE TITLE
Page Cache $key / Protocol Mismatch

### ISSUE THREAD

**Issue by charlesLF** [szepeviktor/fix-w3tc#43]
This issue is to related to something that came up in https://github.com/szepeviktor/fix-w3tc/issues/41#issuecomment-245651854

What I think is happening is the following:

- When an HTTPS page is cached, the cache's `$key` contains "_ssl" in the end.
- When a flush is issued from the backend for a single page, the `_flush_url()` function in `PgCacheFlush.php` does not execute a flush for keys ending with "_ssl".

The culprit is in: 
```php
    function _get_encryptions() {
        $encryptions = array(false);
        if ($this->_config->get_boolean('pgcache.cache.ssl')) {
            $encryptions[] = 'ssl';
        }
        return $encryptions;
    }
```

So, the SSL cache is always created, but never flushed unless "pgcache.cache.ssl" key is set to true (i.e.: "Cache SSL (https) requests" in Performance => Page Cache)

This seems a bit redundant, so we should either enforce the above option and not create a cache entry for SSL pages if this is disabled, OR deprecate this option and always have SSL pages follow the default caching behavior.

**Comment by nigrosimone** [comment]
in PgCache.php method `_get_page_key()` append "_ssl" if  $encryption is passed:
```php
function _get_page_key($mobile_group = '', $referrer_group = '', 
        $encryption = '', $compression = '', $content_type = '', $request_uri = '') {

        // ......................................................

       /**
         * Append encryption
         */
        if ($encryption) {
            $key .= '_' . $encryption;
        }

```

the strange thing is `_get_encryption()` return array:
```php
   /**
     * Returns array of encryptions
     *
     * @return array
     */
    function _get_encryptions() {
        $encryptions = array(false);
        if ($this->_config->get_boolean('pgcache.cache.ssl')) {
            $encryptions[] = 'ssl';
        }
        return $encryptions;
    }
```

this not cause an "Array to string conversion" exception?

**Comment by charlesLF** [comment]
@nigrosimone no, not really.

For the flush case, there's a "foreach" loop:

```php
    function _flush_url($url, $cache, $mobile_groups, $referrer_groups, $encryptions, $compressions) {
        foreach ($mobile_groups as $mobile_group) {
            foreach ($referrer_groups as $referrer_group) {
                foreach ($encryptions as $encryption) {
                    foreach ($compressions as $compression) {
                        $page_key = $this->_get_page_key($mobile_group, $referrer_group, $encryption, $compression, false, $url);
                        $cache->delete($page_key);
                    }
                }
            }
        }
    }
```

**Comment by amiga-500** [comment]
Hi @nigrosimone ! Just had a looksey.  

The `$encryption` variable/parameter sent to `_get_page_key(..)` is indeed a string and is assigned via `_get_encryption()` held inside class  `W3_PgCache` of **PgCache.php**.  The function you are referring to: `_get_encryptions()` (notice the plural "s" at the end) is a function held only inside the class `W3_PgCacheFlush` of **PgCacheFlush.php**

So no array to string exception should occur in this case.

@charlesLF ....ahh i didn't know that w3tc still caches ssl files despite the option being unchecked.  I personally would prefer the option of _"enforce the above option and not create a cache entry for SSL pages if this is disabled"_ since it would be more proper.  I haven't sniffed around for the right spot in `PgCache.php` where the ` if ($this->_config->get_boolean('pgcache.cache.ssl'))` should go so if you know the right spot, feel free.  Otherwise, i will do some digging later on.
