### ISSUE TITLE
Error on line 124 of file Util_File.php

### ISSUE THREAD

**Issue by dnikola** [szepeviktor/fix-w3tc#465]
Hi

i'm ussing WPsolar and sloar server for my wp
w3 total cache Version 0.9.5.2.4 | By W3TC (Fixed) Community |
WordPress Version	4.7.3
PHP Version	7.0.17
WP Memory Limit	1 GB
Max Post Size	128M
Max Upload Size	128 MB
PHP Time Limit	600
Max Input Vars	1000

when i try to index site I'm getting error: 

> Error on line 124 of file /home/xyz/public_html/wp-content/plugins/w3-total-cache/Util_File.php: opendir(/home/xyz/public_html/wp-content/cache/db/options_comments/): failed to open dir: No such file or directory

I checked cache folder
i don't have that folder
i have folder ALL / OPTIONS / COMMENTS but options_comments no

Regards!

**Comment by nigrosimone** [comment]
@dnikola sorry for the long delay.

> Error on line 124 of file /home/xyz/public_html/wp-content/plugins/w3-total-cache/Util_File.php: opendir(/home/xyz/public_html/wp-content/cache/db/options_comments/): failed to open dir: No such file or directory

this is very strange because at line 124 of Util_File.php there is:

`$dir = @opendir( $path );`

the **@** at beginning of `opendir` (thath cause the error) is an error control operators and when prepended to an expression, any error messages that might be generated by that expression will be ignored.

now, the only way for see this error is disable the error control operators with a library called **scream**, http://php.net/manual/en/book.scream.php. If you have **scream** library , try to disable it, eg. in the `wp-config.php` add:

`ini_set('scream.enabled', false);`

Or directly in `php.ini`:

`scream.enabled = Off`

**Comment by nigrosimone** [comment]
@dnikola any news?

**Comment by dnikola** [comment]
Hi

i used disk caching for DB since Siteground didn't had memchaced installed.
We managed to install it and now this work ok with memchaced.
Switching back to disk same problem stay.
Didn't had time to test with this option scream.enabled =off since didn't had library installed.

Regards!

**Comment by nigrosimone** [comment]
ok thanks!
