### ISSUE TITLE
[off] Tiny cache plugin

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#479]
Hello!

I am developing a very tiny (98 sloc) cache plugin
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/tiny-cache

- uses **persistent** object cache
- caches only `the_content()` calls thus most of the HTML body
- for now it only works by replacing `the_content()` in the theme's code

Any thoughts?

**Comment by nigrosimone** [comment]
> caches only the_content()

good idea... i have also developed two small plugin (both are 5 KB):
 - [Speed Up - Menu](https://wordpress.org/plugins/speed-up-menu/): caches only the menu
 - [Speed Up - Translation](https://wordpress.org/plugins/speed-up-translation/): caches only the menu translations (useful for non english wp installation)

i think partial caching is the better way into wp ecosystem. If user need a full cache of all the page, Varnish is the way.

Your idea is good because more themes have visual builder based on shorttag and this introduce a very slow rendering of the page. Maybe, you can cache the_content only if the content has a shorttag.

**Comment by szepeviktor** [comment]
Thank you!

A *tiny* style translation cache plugin is worth considering. Featuring purge and proper keys.

> Maybe, you can cache the_content only if the content has a shorttag.

Don't forget about `the_content` filter, it does heavy lifting too.

**Comment by szepeviktor** [comment]
Thank you again for the insiration:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/tiny-cache

This is the_content() cache:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/tiny-cache

**Comment by szepeviktor** [comment]
Improved and moved to a separate repo: https://github.com/szepeviktor/tiny-cache
