### ISSUE TITLE
Enabling page cache causes errors in test

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#511]
Enabling page cache without a page-caching plugin activated causes warnings in test.

Cause https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/bin/install-wp-tests.sh#L95
Symptom https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/248516716#L444

**Comment by nigrosimone** [comment]
it seem just a problem with the test logic, maybe the plugin is loaded in the wrong point of the test workflow (too soon) and the environment is not correctly initializated.

I have added a set of test (https://github.com/szepeviktor/w3-total-cache-fixed/pull/512) just for check that the necessary files are in the right place when the test runs.

**the errors are still present, but when the tests runs, all file are in the right place, otherwise test fail.**

**Comment by nigrosimone** [comment]
https://github.com/szepeviktor/w3-total-cache-fixed/pull/512

**Comment by szepeviktor** [comment]
https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/250114984
It would be simple to solve: not to set `WP_CACHE` until w3tc is activated.

**Comment by nigrosimone** [comment]
mhhh without WP_CACHE wordpress don't use cache...

**Comment by nigrosimone** [comment]
maybe we can set WP_CACHE at beginning of the test... https://github.com/szepeviktor/w3-total-cache-fixed/pull/513

**Comment by nigrosimone** [comment]
doesn't works

**Comment by szepeviktor** [comment]
Yes, because WP boots up before the test.
