### ISSUE TITLE
Removing SVG from HTML mime file

### ISSUE THREAD

**Issue by prayagverma** [szepeviktor/fix-w3tc#531]
Sorry for my lack of knowledge. I am facing issues with speed tests (like GTMetrix)  relating to SVG files not having a cache validator. After searching around, I found that this was related to `inc/mime/html.php`  I tried to search for related issues and found that this was fixed in https://github.com/szepeviktor/w3-total-cache-fixed/pull/271  but then via discussions in https://github.com/szepeviktor/w3-total-cache-fixed/issues/292 it was later rejected. I wanted to ask will this be implemented again? Was this done because SVG is not considered a static resource but a dynamic resource?

**Comment by nigrosimone** [comment]
> Was this done because  SVG is not considered a static resource but a dynamic resource?

Official W3TC has discarted #271 because:

> .svg files have regular xml syntax on correctly configured web servers/valid files.

If you want, you can reintroduce the fix yourself by editing `inc/mime/html.php` in this way https://github.com/szepeviktor/w3-total-cache-fixed/pull/271/files

> I wanted to ask will this be implemented again? 

no... we try to take the plugins versions very close. If one community custumization is discarted, we accept it and not reintroduce.
