### ISSUE TITLE
Official W3TC has been updated to 0.9.6

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#546]
The Official W3TC has been updated to 0.9.6 with so many W3TC-FIX fixes, improvements and enhancements. 

   Fixed anonymous usage tracking, default to disabled
   Fixed incorrect minify cache data written if target directory missing
   Fixed empty minify cache file written when file locking enabled
   Fixed missing commas in CSS (@nigrosimone)
   Fixed typo in object cache engine (@Furniel)
   Fixed incorrect reuse of redis connections when persistent connections option enabled
   Fixed reliability of Google Drive (via @jikamens)
   Fixed handling of UTF-8 encoded files by writing them in binary (via @jikamens)
   Improved Full Site Delivery configuration user flow on the General and CDN settings screens
   Improved content type matching and cache hits as a result
   Improved minify file locking logic
   Improved visual langage of the compatibility test (@Furniel)
   Improved configuration file management
   Improved MaxCDN set up wizard
   Improved page cache’s accepted query string handling to handle optional values and add support for disk enhanced mode (via @amiga-500, @nigrosimone)
   Improved handling of timeouts to origin push CDN proviers
   Added HTTP/2 push headers for disk enhanced page caching (via @nigrosimone)
   Added X-Forwarded-Proto header for use cases like HTTPS recognition behind proxies or load balancers
   Added multiple CDN support i.e. static file objects and pages, posts, feeds, API responses etc to use different respective CDN providers
   Added page caching by cookie name or value (sponsored by SQweb)
   Added toggle for CORS header to improve inter-operatbility with various CDN providers
   Added support for CDN hosted media to media library (inspired by @amiga-500)
   Added object caching of AJAX calls (via @andyexeter)
   Enterprise features are now available to Pro subscribers! Including reading from multiple databases concurrently and purging caches across multiple hosts via a Message Bus

see https://wordpress.org/plugins/w3-total-cache/#developers

Anyone can help me to check if there are all [w3tc-fix changes](https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog)?

I'm checking the changes and the official w3tc seems to have all community fixes.

from latest PRs:
https://github.com/szepeviktor/w3-total-cache-fixed/pull/537 OK 
https://github.com/szepeviktor/w3-total-cache-fixed/pull/527 OK
https://github.com/szepeviktor/w3-total-cache-fixed/pull/522 OK
https://github.com/szepeviktor/w3-total-cache-fixed/pull/523 PARTIAL
https://github.com/szepeviktor/w3-total-cache-fixed/pull/524 OK
https://github.com/szepeviktor/w3-total-cache-fixed/pull/525 NO
https://github.com/szepeviktor/w3-total-cache-fixed/pull/520 OK

for knowledge, all contributors @szepeviktor, @charlesLF, @archon810, @andyexeter, @marian-kadanka, @raphaelquati, @niklasfink, @sbutler, @Crevil, @viawest-davidsix, @mrosenberg, @jikamens, @amiga-500, @Furniel

**Comment by szepeviktor** [comment]
Nice from Frederick that he follows our repo.

Personally I run all websites on [cloud servers](https://www.upcloud.com/register/?promo=U29Q8S) providing Redis cache. So for caching WordPress **post content, translations and nav menu output** I've developed Tiny cache and [Tiny CDN](https://wordpress.org/plugins/tiny-cdn/).
You can find it here https://github.com/szepeviktor/tiny-cache

**Comment by andyexeter** [comment]
The only thing I’d mention about my PR #537 is that the description isn’t really accurate.

The PR fixes object caching of arbitrary data _within_ AJAX calls, rather than adding object caching of AJAX calls :)

**Comment by szepeviktor** [comment]
See https://github.com/szepeviktor/w3-total-cache-fixed/pull/537 again :)

**Comment by andyexeter** [comment]
I mean in the release notes, it says “Added object caching of AJAX calls” which isn’t quite right :)

**Comment by szepeviktor** [comment]
[Fixed](https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog)

**Comment by charlesLF** [comment]
Cool

We'll have to spend a bit of time identifying and reconciling the differences in both codes.

EDIT: doesn't look too bad. I can take care of this sometime in the next couple of days.

*Here is a checklist for you*

- [ ] [Dashboard Widget For Flushing Individual User-Inputted URLs](https://github.com/szepeviktor/w3-total-cache-fixed/commit/f098003e8e4b4a3dbc2504b8a47b62205d5f6b9b)<br>:wrench: [+ **Extra: #PR335** &ndash; Adds Missing Nonce check](https://github.com/szepeviktor/w3-total-cache-fixed/pull/335)
- [ ] [Gzipped Cached Pages Are Not Decoded Correctly &ndash; PHP 5.3.x Specific](https://github.com/szepeviktor/w3-total-cache-fixed/pull/313)
- [ ] [_{uploads_dir}_ Placeholder & Full URLS Issue In CDN Custom Files Field](https://github.com/szepeviktor/w3-total-cache-fixed/pull/316)
- [ ] [CSSTidy Updated to v1.5.5 With New Options &ndash; Requires PHP 5.4+](https://github.com/szepeviktor/w3-total-cache-fixed/pull/317)
- [ ] [Google PageSpeed Widget &ndash; Key Restriction Field Added](https://github.com/szepeviktor/w3-total-cache-fixed/pull/318)
- [ ] [Page Cache &ndash; Added 4 New "_Never Cache ..._" Fields](https://github.com/szepeviktor/w3-total-cache-fixed/pull/319)<br>:wrench: [+ **Extra: #PR320** &ndash; Adds Missing Check for Page & Post Type](https://github.com/szepeviktor/w3-total-cache-fixed/pull/320)
- [ ] [Admin Image URLs Malformed For Must-Use Plugins (mu-plugins)](https://github.com/szepeviktor/w3-total-cache-fixed/pull/322)
- [ ] [WP-CLI &ndash; Prime the Page Cache (Cache Preload)](https://github.com/szepeviktor/w3-total-cache-fixed/pull/324)
- [ ] [Flushing Not Working Consistently For Post Changes](https://github.com/szepeviktor/w3-total-cache-fixed/pull/331)
- [ ] [Amazon Web Services (AWS) Signature v4 Support & New Locations](https://github.com/szepeviktor/w3-total-cache-fixed/pull/332)
- [ ] [Save Cloudflare Settings &ndash; SSL Update Failure](https://github.com/szepeviktor/w3-total-cache-fixed/pull/334)
- [ ] [Rewrite URLs via _wp_..._attachment_for_js()_ filter when CDN is Enabled](https://github.com/szepeviktor/w3-total-cache-fixed/pull/336)<br>:wrench: [+ **Extra: #PR350** &ndash; Checkbox to Use CDN URLs for Media Library](https://github.com/szepeviktor/w3-total-cache-fixed/pull/350)
- [ ] [Malformed HTML in Generated Item UIs (Admin Pages)](https://github.com/szepeviktor/w3-total-cache-fixed/pull/343)
- [ ] ["Security Headers" Section Added to Browser Cache](https://github.com/szepeviktor/w3-total-cache-fixed/pull/344)<br>:wrench: [+ **Extra: #PR363** &ndash; Adds Default Values to CSP (Security Headers)](https://github.com/szepeviktor/w3-total-cache-fixed/pull/363)<br>:wrench: [+ **Extra: #PR377** &ndash; Important Change &ndash; Session Cookies](https://github.com/szepeviktor/w3-total-cache-fixed/pull/377)<br>:wrench: [+ **Extra: #PR436** &ndash; Add referrer policy security header](https://github.com/szepeviktor/w3-total-cache-fixed/pull/436)
- [ ] [W3TC is Collecting Tracking Usage At All Times](https://github.com/szepeviktor/w3-total-cache-fixed/pull/349)
- [ ] [Additional Home URLs (set in Page Cache) not Purging](https://github.com/szepeviktor/w3-total-cache-fixed/pull/357)
- [ ] [Configuration Bug &ndash; Redis/Memcached Server Entries](https://github.com/szepeviktor/w3-total-cache-fixed/pull/367)
- [ ] [Undefined Variable: _is_amp_endpoint_](https://github.com/szepeviktor/w3-total-cache-fixed/pull/370)
- [ ] [Error Message: _Trying to Get Property of Non-Object_](https://github.com/szepeviktor/w3-total-cache-fixed/pull/376)
- [ ] [Page Cache &ndash; _Accepted Query Strings_ Enhancement](https://github.com/szepeviktor/w3-total-cache-fixed/pull/380)<br>:wrench: [+ **Extra: #PR489** &ndash; Fix all querystring keys starting with name specified will match](https://github.com/szepeviktor/w3-total-cache-fixed/pull/489)
- [ ] [Incorrect Use of Removing Query String From URLs](https://github.com/szepeviktor/w3-total-cache-fixed/pull/382)
- [ ] [Enhance _remove_query()_ to Recognize Other Ampersand Forms](https://github.com/szepeviktor/w3-total-cache-fixed/pull/383)
- [ ] [WP Query String Being Stripped Unexpectedly](https://github.com/szepeviktor/w3-total-cache-fixed/pull/384)
- [ ] [Filter to Set Cache Lifetime Period On A Per-Page Basis](https://github.com/szepeviktor/w3-total-cache-fixed/pull/388)
- [ ] [Warning: _Invalid Arguments in Minify_Environment.php_](https://github.com/szepeviktor/w3-total-cache-fixed/pull/389)
- [ ] [Feeds Not Caching Nor Serving Back as XML](https://github.com/szepeviktor/w3-total-cache-fixed/pull/393)<br>:wrench: [+ **Extra: &ndash; Fix admin setting always disabled on nginx](https://github.com/szepeviktor/w3-total-cache-fixed/pull/454)
- [ ] [Smart Browser Cache Default Settings](https://github.com/szepeviktor/w3-total-cache-fixed/pull/394)<br>:wrench: [+ **Extra: #PR395** &ndash; A Few More Useful Smart Default Settings](https://github.com/szepeviktor/w3-total-cache-fixed/pull/395)
- [ ] [Expanded Regex Support & Improved Page Cache Cookies](https://github.com/szepeviktor/w3-total-cache-fixed/pull/398)
- [ ] [Debug Mode Not Working](https://github.com/szepeviktor/w3-total-cache-fixed/pull/405)<br>:wrench: [+ **Extra: #PR406** &ndash; Missed File - Debug Mode Not Working](https://github.com/szepeviktor/w3-total-cache-fixed/pull/406)
- [ ] [PHP Deprecation Notice &ndash; _is_comments_popup()_](https://github.com/szepeviktor/w3-total-cache-fixed/pull/407)
- [ ] [_W3TC-Include-JS-Head_ Tag Implementation Missing For Auto Mode](https://github.com/szepeviktor/w3-total-cache-fixed/pull/401)
- [ ] [Catch Exceptions Thrown When Saving Config](https://github.com/szepeviktor/w3-total-cache-fixed/pull/408)
- [ ] [Fix feeds on the dashboard](https://github.com/szepeviktor/w3-total-cache-fixed/pull/413)
- [ ] [Make the dashboard responsive](https://github.com/szepeviktor/w3-total-cache-fixed/pull/414)
- [ ] [Deprecated the "Allow, Deny, and Order" directives](https://github.com/szepeviktor/w3-total-cache-fixed/pull/418)
- [ ] [Util_Environment::document_root() On Windows return "/" instead of "\\"](https://github.com/szepeviktor/w3-total-cache-fixed/pull/422)
- [ ] [Customize Cache Directory](https://github.com/szepeviktor/w3-total-cache-fixed/pull/423)
- [ ] [YUI Compressor fix for JAVA path](https://github.com/szepeviktor/w3-total-cache-fixed/pull/426)
- [ ] [Closure Compiler fix for JAVA path](https://github.com/szepeviktor/w3-total-cache-fixed/pull/428)
- [ ] [Fixed Redis Test on Admin Dashboard](https://github.com/szepeviktor/w3-total-cache-fixed/pull/430)
- [ ] [Extends "http 2 push" to page cache enhanced](https://github.com/szepeviktor/w3-total-cache-fixed/pull/433)<br>:wrench: [+ **Extra: #PR320** &ndash; Support for more than 50 assets](https://github.com/szepeviktor/w3-total-cache-fixed/pull/450)<br>:wrench: [+ **Extra: #PR491** &ndash; Fix collects headers from top directory](https://github.com/szepeviktor/w3-total-cache-fixed/pull/491)
- [ ] [Fixed Object Cache setting cache value on missed gets](https://github.com/szepeviktor/w3-total-cache-fixed/pull/439)
- [ ] [Call to a member function using_index_permalinks() on null](https://github.com/szepeviktor/w3-total-cache-fixed/issues/445)
- [ ] [stristr(): Empty needle](https://github.com/szepeviktor/w3-total-cache-fixed/issues/447)
- [ ] [Media Library Export skips files](https://github.com/szepeviktor/w3-total-cache-fixed/pull/452)
- [ ] [Fixed semicolon bug & added woff2](https://github.com/szepeviktor/w3-total-cache-fixed/pull/457)
- [ ] [Copy&paste comment in opcache.php](https://github.com/szepeviktor/w3-total-cache-fixed/pull/387)
- [ ] [Colored self test window](https://github.com/szepeviktor/w3-total-cache-fixed/pull/478)
- [ ] [Fixed Redis DB selection in persistent connection mode](https://github.com/szepeviktor/w3-total-cache-fixed/pull/483)
- [ ] [Fixed wrong == in ObjectCache_WpObjectCache_Regular.php](https://github.com/szepeviktor/w3-total-cache-fixed/pull/486)
- [ ] [Missing commas in Generic_Page_Dashboard_View.css](https://github.com/szepeviktor/w3-total-cache-fixed/pull/487)
- [ ] [Remove uninitialized variable](https://github.com/szepeviktor/w3-total-cache-fixed/pull/488)
- [ ] [Fix page cache .htaccess for Windows](https://github.com/szepeviktor/w3-total-cache-fixed/pull/490)
- [ ] [Fix Undefined property: W3TC\\Extension_Amp_Plugin::$is_amp_endpoint](https://github.com/szepeviktor/w3-total-cache-fixed/pull/510)
- [ ] [Adjusting cdn link in MediaLibrary](https://github.com/szepeviktor/w3-total-cache-fixed/pull/516)
- [ ] [Add support for X-Forwarded-Proto to identify HTTPS protocol](https://github.com/szepeviktor/w3-total-cache-fixed/pull/520)
- [ ] [Fix a timeout update that was missed in push CDN upload](https://github.com/szepeviktor/w3-total-cache-fixed/pull/525)
- [ ] [Write correct data into minify cache file when cache dir is created](https://github.com/szepeviktor/w3-total-cache-fixed/pull/524)
- [ ] [Make the Google Drive CDN work properly](https://github.com/szepeviktor/w3-total-cache-fixed/pull/523)
- [ ] [Return correct data from minify file cache when locking is in use](https://github.com/szepeviktor/w3-total-cache-fixed/pull/522)
- [ ] [Write cache files in binary to prevent corruption of UTF-8 characters](https://github.com/szepeviktor/w3-total-cache-fixed/pull/527)
- [ ] [Fix object caching of arbitrary data within AJAX calls](https://github.com/szepeviktor/w3-total-cache-fixed/pull/537)

**Comment by szepeviktor** [comment]
@charlesLF I've added a list into your comment.

**Comment by lvl99** [comment]
Just a question: is the official W3 Total Cache plugin catching up to this version of the plugin, or does this version of the plugin need to incorporate aspects of the official plugin?

I keep getting a reminder from Wordfence to update W3TC, but I'm waiting for a v0.9.6 release on this repo, rather than use the official...

**Comment by charlesLF** [comment]
Too many differences, too little time.
I will keep using the v0.9.5.x branch on this repo since it's working just fine in all my setups.

Anyone else up to reconciling the differences?

**Comment by cre8gr** [comment]
Well,

The plugin has a serious issue that the developer has yet to fix it. Too much error 500.

See here for details: [https://wordpress.org/support/topic/fatal-error-2749/](https://wordpress.org/support/topic/fatal-error-2749/)

Most of the people I know haven't updated, or reverted to the previous version because of it.

**Comment by nigrosimone** [comment]
@cre8gr this is my fix https://wordpress.org/support/topic/fatal-error-2749/#post-9779929

**Comment by nigrosimone** [comment]
@charlesLF

> Too many differences, too little time.

true... i have also tried ... it's a mission inpossible for me.

**Comment by Furniel** [comment]
Descided to help and reviewed all commits and picked missing or in some cases partially missing to 0.9.6.x_wip branch. All other commits were already merged to 0.9.6 or in some cases bugs were fixed in other way. And i skipped commits that were changing only readme files(for new release they should be rewritten).

PS: I don't use wordpress in my projects at this moment, so i can't test new version and check how it works.

**Comment by nigrosimone** [comment]
hi @Furniel thanks again! great work!

**Comment by nigrosimone** [comment]
@szepeviktor, @Furniel has merged Fixed version with last official version into 0.9.6.x_wip branch. In the past you have made the switch, you can made the same magic?

**Comment by szepeviktor** [comment]
@Furniel Thank you.
This is the default branch now.

**Comment by szepeviktor** [comment]
@nigrosimone Could you please double-check that 56f1c452fcdaf7631d893fd5dcbf44d27a7fc085 is really bit-by-bit equal to WP.org zip?

**Comment by nigrosimone** [comment]
@szepeviktor, @Furniel the https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.6.x_wip/README.md is out of sync with https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog.

It seem we have lose the last 14 PR. in the readme.md the last update is "Colored self test window", in the wiki "Fix object caching of arbitrary data within AJAX calls". What happened?

**Comment by szepeviktor** [comment]
The readme was updated on dec. 24. https://github.com/szepeviktor/w3-total-cache-fixed/commits/v0.9.6.x_wip/README.md

**Comment by Furniel** [comment]
@nigrosimone 
As I mentioned earlier, readme files should be updated(rewritten) for new branch. For example "Fix object caching of arbitrary data within AJAX calls" commit was merged by w3tc devs and original 0.9.6 version contains this commit. As result i skipped original commit and it was not merged to 0.9.6_wip branch and README.md is not updated and does not contain `:beetle: Bug Fix | [Fix object caching within AJAX requests](https://github.com/szepeviktor/w3-total-cache-fixed/pull/537) |` line. 

As mentioned in readme.md it contains changes `Since the last official release of W3 Total Cache (v0.9.5.2)` and i think that for 0.9.6 branch it should be rewritten and contain changes since 0.9.6 release, but on wiki page should be mentioned **all changes** by w3-total-cache-fixed contributors(that were or not merged by w3tc devs).

**Comment by szepeviktor** [comment]
This reasoning seems reasonable :)

**Comment by szepeviktor** [comment]
@nigrosimone Hello!
Are you proceeding with the new release?

**Comment by nigrosimone** [comment]
I'm a bit busy now, but i have 2 bug fix ready over the last official release.

**Comment by szepeviktor** [comment]
@nigrosimone Thank you for the release.

**Comment by nigrosimone** [comment]
@szepeviktor i have found a bit of time for made the new release :D
