### ISSUE TITLE
Wordpress Adoption Program for Abandoned Plugins

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#57]
FIX-W3TC Guys! I have read this [post ](https://digwp.com/2012/10/abandoned-plugin-adoption-program/) about  "Wordpress Adoption Program for Abandoned Plugins" that i found interesting.

We could try to adopt W3TC?

**Comment by Tarun80** [comment]
Just an end user here but I'd say please do try to! I'd love to see your version on the official Wordpress plugin pages. It works beautifully on my dev environment.

**Comment by amiga-500** [comment]
@Tarun80 that's awesome to know it works well for you!  Thanks for the feedback!  Yea adopting would be really nice.  It certainly would help reduce the amount of new support thread posts about bugs that were fixed long ago.

Cheers
Kimberly

**Comment by nigrosimone** [comment]
my english is really poor, anyone is interested to contact plugins@wordpress.org ?

**Comment by amiga-500** [comment]
> my english is really poor, anyone is interested to contact plugins@wordpress.org ?

Hi @nigrosimone!  About 3 days ago I actually did contact plugins@wordpress.org as well as a few other addresses with a lengthy, impassioned plea explaining the hopes of adoption by the crew here in this repository.  I provided links such as this github, links to some of our backgrounds and relevant experiences in coding, and numerous direct evidence of neglect and abandonment by the original author in the official support forum, etc.  

I promptly got back a response from Wordpress (a rep named: Mika Epstein). Her response was very direct and absolute:

> _Not gonna happen._
> 
> _I'm sorry, but this is one plugin we're not even going to consider handing over. You can fork it if you want, but we won't be letting anyone adopt it._
> 
> _We'll let the devs know folks have asked and we've declined, but this is one of the plugins that it's actually WORSE if we gave it to someone else :/ It would have to be a company like Sucuri or Automattic to even consider it._

So apparently adoption is out of the question :(  I also tried in vain (like so many) to contact @ftownes.  The hope being that a dialogue could be started to figure out if Frederick would be open to the idea of allowing someone to adopt w3tc.  But to no surprise the man is officially a ghost online; every form of contact path to him is a dead end.

Regards
Kimberly

**Comment by Tarun80** [comment]
That seems way too stone cold of a response and not very professional. Way too short, no explanations as to why it cannot be handed over, etc. I'd be tempted to seek clarification.

On the plus side, you can fork it and put it up there!

**Comment by Volnus** [comment]
I can see the reasoning behind this letting a team of random developers like us take over one of the most popular plugins in the entire WordPress ecosystem is not an intelligent move and I can see the reasoning behind requiring a company to take it over. They have the structure to manage it properly and improve it. 

Therefore I have to agree with their response here it would be good to see a company adopt it such as Sucuri, or Automattic ~

**Comment by anan5002** [comment]
Well, if it is cant me adopted, then it is best to fork it and let it live with new name.

**Comment by nigrosimone** [comment]
need attention from @Automattic @Sucuri

**Comment by nigrosimone** [comment]
@anan5002 the major part of code isn't ours. It is not ethical to copy and publish it with a new name.

**Comment by rabin-io** [comment]
@nigrosimone isn't that what open source and GPL is all about ? the original developer left the plugin/code without support, and the community is trying to pick up from where he left.  it's not like you are trying to monetize this plugin.

**Comment by dreadedhamish** [comment]
There are a few issues:
1. Over 1 million sites have the plugin installed - giving a group of devs permission to give updates to all these people would need an incredible level of trust from the wp team.
2. The original author hasn't formally given up.

**Comment by anan5002** [comment]
@nigrosimone i agree. i hope the original developer can turn up and give his permission / hand over this to you guys who can maintain it.

**Comment by nigrosimone** [comment]
Now 1'000'000 of wordpress site have a security hole (#79) without any hope of future update.

**Comment by amiga-500** [comment]
I decided to email Wordpress about it just now making them aware of how all 1 million are vulnerable and how the fix-w3tc project was quick to patch it (thank you @cesco69 !).

I am just too damn curious to see what they do and/or how they respond.  I hope they patch it.  And it should be quick for them since they have a source file to copy from (ours).

If they respond i'll post it here.

Regards
Kimberly

**Comment by MarceloPedra** [comment]
Hello guys, I've been following this fork and it's very nice to see it working. 

Now to my question: If the plugin is released under GPL, why cannot you guys upload it to WP repo with a similar name? "W3 Total Cache Recoded" or something alike? If @ftownes appears to be no longer interested in the project, I don't see why 1M users shouldn't have the option to uninstall it and install a working plugin.

Regards
Marcelo

**Comment by nigrosimone** [comment]
@amiga-500 @charlesLF @szepeviktor @volnus 

we are the most active developers. make a new plugin seems the only way. 

What do you think about this?

**Comment by Moonomo** [comment]
Currently, folks don't find a plugin that they can move into, by dropping W3TC, which offers similar or same features (at least they don't find FREE alternative easily, if there is any).

I thought few years back, when I start hitting issues with W3TC, to fork and maintain my own version. Then dropped it instead, and optimized my server/plugins/theme to not needing one.

I think if you really have the time to maintain it in the future, please take the time to fork it- release a new plugin with similar name, or keep some relevant notes so people find your plugin when they search for W3TC on WordPress plugin directory. That would be really awesome!

**Comment by szepeviktor** [comment]
Mika got it right.
There are a lot of use cases of W3TC, I am mostly thinking of enterprise usage and API calling.

AFAIK W3TC has continuous integration system which is not published.
The mentioned *company* should have a throughout test suite like in https://github.com/wp-cli/wp-cli/blob/master/.travis.yml and at least 1 developer who is assigned to W3TC.

Basically I think we need
- higher code quality
- peer review
- maybe WPCS code styling
- CI with >80% coverage
- WP.org release thus user base who may give signals

It means we have to have some profit to back it up.

**Comment by szepeviktor** [comment]
> We’ve added tens of thousands of unit tests for the various bugs and improvements

Frederick Townes
https://wptavern.com/frederick-townes-confirms-w3-total-cache-is-not-abandoned

**Comment by nigrosimone** [comment]
@szepeviktor you are right...

**Comment by Tarun80** [comment]
I'd say release it under GPL as stated above. You've already put a lot of work into it and patched security bugs _very_ quickly that would otherwise be forgotten/ignored by the original author.

That article that @szepeviktor posted was from March of this year. Over six months ago and still no update to the actual code.

From the Wordpress page today:
Compatible up to: 4.5.4
Last Updated: 6 months ago

Now, looking at the activity on this plugin. No code has been updated for almost **two years**! I do not see changing a compatibility number as an update/change. That is, going from 4.4 to 4.5 in readmes for compatibility.

Let's dig a bit deeper and look at this further. The last actual update was a security fix on 2014-12-10.

https://plugins.trac.wordpress.org/changeset/1041802

Being an open sourced plugin you'll get a large sample of data and servers/tests that users will run this on, along with many willing to contribute and assist in resolving issues. You've also made this PHP7 compatible.

Keep up the great work and don't feel discouraged, you guys have a great thing going and I look forward to seeing it shared with the world and on the Wordpress Plugin site.

**Comment by vijayaraghavanramanan** [comment]
Yeah, you could release it as a separate plugin with a different name such as W3 Total Cache Fixed.

**Comment by szepeviktor** [comment]
Anyone up to answering the support questions of non-technical users on WP.org within a couple of days?

**Comment by MarceloPedra** [comment]
@vijayaraghavanramanan: Now that I readed the code, I'm not _really_ sure if you can use the entire string of the original name. If you see this link, you will notice Townes alleged some kind of copyright:
https://github.com/szepeviktor/fix-w3tc/blob/master/w3-total-cache.php#L12

So, maybe the entire code is released under GPL, but THE PLUGIN NAME might be owned by him or his company as a trademark. Does anybody know how to check this out? Any public trademark directory where one can lookup this?

**Comment by Tarun80** [comment]
Less than an hour ago, an update landed:

https://plugins.trac.wordpress.org/changeset/1502416

**Comment by nigrosimone** [comment]
Yep!

**Comment by anan5002** [comment]
at last the author have updated the plugin. Does it covers all the community driven changes done so far?

**Comment by MarceloPedra** [comment]
Yes, lots of fixes and a file structure redesign. Much of the fixes are the same fixed by this fork. Have they forked the fork?

**Comment by vijayaraghavanramanan** [comment]
Maybe not but seems to have solved the AMP issue. If I remember from the forums, the AMP issue was the one which led to this Github. 

In the latest Yoast SEO, there's no priority but W3TC needs priority for priming. One fix needed in the original. So, It has been fixed here but not there.

**Comment by Tarun80** [comment]
I hope you all are able to come up with a name and submit this fork of your own. The speed of the fixes, correction of features, and the speed the exploit was fixed is something that should be critical to many webmasters. Though new here, I've looked over all the coding and commits and it's really refreshing to see a team committed to quality assurance and being so quick to fix exploits.

**Comment by Ipstenu** [comment]
I wanted to step in and give you an overview for free. In order for a fork of this nature to be considered, you've got a long road of clean up including (but not limited to):

* Review every line of code to ensure it would pass a review today. Frankly, a lot of W3TC is non-optimal, though this is true of most code 5+ years old.
* Ensure an 'upgrade' or 'migration' path - So that if I'm using W3TC, I can remove it, install yours, and my site will keep running. (Otherwise no one will adopt your plugin.)
* Remove all trademark protected content (that means remove the terms "W3 Total Cache" and "W3TC", all images, etc). If you're not sure, remove it. _Assume_ they trademarked their name. Even if they don't, we won't let you use someone else's brand.
* Remove all calls back to their services (no brainer ;) )
* Change all support links
* _RETAIN_ all copyrights - that is you must credit W3TC in source code and (preferably) the readme as well.
* Come up with an original name. While "Fix W3TC" would _technically_ be passable for the repo, it's not unique. If you're going to fork this, do it all the way and fork it. Rename it, rebrand it, and make it your own.

And worst ... you have to add something 'new.' Otherwise you're a copy, not a fork. Just removing all the premium features is a good start, but we'd want to see some evidence that there IS a plan for the plugin. A path that you see to make it better in an ongoing way.

Personally ... I would like to see someone have a W3TC killer.

**Comment by nigrosimone** [comment]
Hi Mika! happy to see you here!

**Comment by jkirker** [comment]
I'm VERY interested in following this.  Thanks for your work!  Will start testing this as an alt to W3TC in dev this week.

**Comment by ftownes** [comment]
Sorry in advance if anyone finds this post to be inappropriate:

If anyone is interested in contributing directly to the project, that option has always been available and there have been various contributors over the years. We had planned to open up the repository to the public closer to public release, but could be convinced to change that plan.

If you'd like to join the repository, please let me know. Also if you're curious about the architecture or other changes in the latest release (which are substantial over previous releases), please let me know as well.

**Comment by szepeviktor** [comment]
> If you'd like to join the repository, please let me know.

@ftownes I would occasionally fix popular WP.org Support issues.

**Comment by ftownes** [comment]
@szepeviktor thanks, I'll send you an email as well, so we can catch up!

**Comment by charlesLF** [comment]
Hello @ftownes, glad to see you here!

I think there are a few of us here that may be interested in joining the repository. I can only speak for myself, but the top contributors here include @amiga-500 , @nigrosimone , and me.
Are you still considering putting it on github? Perhaps as a private invite-only repository at first before having it open to the public with the v1.0 release?

I also think that we need to clear out a few things (such as the lack of public communication that happened over the past year or so, lack of premium support to those who paid for the plugin, etc...), before jumping into anything. I will refer you to a previous comment that I made (https://github.com/szepeviktor/fix-w3tc/issues/112#issuecomment-249657651) that is perhaps better phrased  :)

**Comment by nigrosimone** [comment]
Hi @ftownes, happy to see you here! I like to join in the repository.

**Comment by rabin-io** [comment]
Hello @ftownes , I also like to have access to the repository.

Thanks,

**Comment by Volnus** [comment]
@ftownes I would like to join as well I handle more of the support on the forum but I can throw my hat into the game and provide bug reports when they come up.

**Comment by Tarun80** [comment]
My question is... What is going to happen to this fork?

**Comment by szepeviktor** [comment]
If we find on items for https://github.com/szepeviktor/fix-w3tc/issues/116 then it'll be abandoned.

**Comment by Volnus** [comment]
I can agree with this path there is no reason to continue a fork if the actual one can be maintained and fixed, and supporter properly.

**Comment by Tarun80** [comment]
I don't believe it should be abandoned honestly. There have been quality features and things introduced into this fork - including the speed of exploit fixes - that made it a great choice when the codebase was abandoned for two years.

Competition leads to innovation. You've also heard what needs to be done to have this fork officially supported.

**Comment by Volnus** [comment]
True but all the features we have created as far as I can tell have been integrated into the main plugin and the speed of exploit fixes would increase in the event of being able to work on the main repository.

**Comment by Tarun80** [comment]
And he is also the only one currently able to submit plugin updates to Wordpress, correct?

Was there also not some discussions saying that many fixes were taken from Fix-W3TC and put into W3TC? Was there credit given? (I did not look into this much, I admit)

The fork is great. You have a team that will be very supportive and works well together. Both on the code side and public/support side.

I'm looking at all things realistically. As the expression goes, history does repeat itself.

**Comment by jkirker** [comment]
What about PHP7 w/ the "official" ver?

**Comment by szepeviktor** [comment]
Please see the changelog, it is public
https://github.com/szepeviktor/fix-w3tc/blob/52e807303252c5c6278a59850ba7ebec26746953/readme.txt#L812

**Comment by amiga-500** [comment]
> What about PHP7 w/ the "official" ver? 

Results from the the _[PhpCompatibility](https://github.com/wimg/PHPCompatibility)_ tests
### w3tc v0.9.5 (official)
```
PHP 7.0: 67 errors, 57 warnings
PHP 5.6: 4 errors, 74 warnings
PHP 5.5: 5 errors, 74 warnings
PHP 5.4: 5 errors, 57 warnings
PHP 5.3: 7 errors, 57 warnings
```
### fix-w3tc
```
PHP 7.0: 0 errors, 0 warnings
PHP 5.6: 0 errors, 0 warnings
PHP 5.5: 0 errors, 0 warnings
PHP 5.4: 0 errors, 0 warnings
PHP 5.3: 0 errors, 0 warnings
```

**Comment by Tarun80** [comment]
What @amiga-500 posted shows one solid reason for keeping the fork going. Smooth code is wonderful.

**Comment by rabin-io** [comment]
Another way is to open the plugin development to the public, and this way allow other people to contribute , some peoples can help with small stuff,  and this way remove some of the burden from the main developers.

**Comment by FPCSJames** [comment]
Hi there @ftownes - glad to see you here. I've been following this fork pretty closely even though I haven't (yet) contributed anything. I support the idea of a public GitHub repo, but in lieu of that I'd like to be a part of the private group. I have some ideas about modularity I've been playing around with that could be useful going forward.

**Comment by Tarun80** [comment]
After reviewing the support forum on WordPress for W3TC I've seen a _**LOT**_ (at least seven pages as of this post) of people having all kinds of problems ranging from PHP issues, configuration issues, and server issues where it has flat out caused their server performance to degrade poorly. There are even screenshots from users that need help, trying to show the problems they're having as you can see [here](https://i.imgur.com/idi1smA.png).

Something else that has caught my eye is that there has been no support from the author on these issues, despite the talks of testing. Tie this in with how the prices for support increased by an absurdly disgusting amount.

- Email from 75 to 175 (increase of 100)
- Phone from 150 to 250 (increase of 100)
- Plugin Config from 100 to 200 (increase of 100)
- Theme config from 150 to 350 (increase of 200)
- Linux config from 200 to 450 (increase of 250)

Based on numerous things I've been reading and researched thus far. This is the first update in nearly **_two years_**. Much of the code is causing issues and problems for users. Some versions of PHP seem as though they are no longer supported (having high errors) and there was no mention of this in the changelog. Even Kimberly posted showing that W3TC official has numerous errors and warnings with the PHP code for PHP7/5.x compatibility whereas Fix W3TC has no errors or warnings! Some of the code was taken from this repository. (I'm still looking into if credit was given for the code being used from the GPL fork.) In a near two year span, it gives the impression that little to none of this code was tested on various developer environments as it should have been.

I even had issues with the update from W3TC 0.9.4.1 to 0.9.5 official. Many of my settings were completely wiped out. Gone. I had to reset 80% of the setting configurations I made. User settings should not be reset they should be preserved.

What I do see is that many people are pointing them to use this version - _Fix W3TC_ - and the vast majority of people are _very happy_ that they made the switch.

It really looks like there was a push to make this update because Fix W3TC was making great progress and looking to adopt the plugin. That in turn made a push on W3TC to get something out the door, and also allow a reason to raise the prices. Which makes me wonder, was this truly a worthwhile fix or an excuse to raise prices by releasing a broken product?

On the subject of switching to Fix W3TC; I'm evaluating what all will change when I switch away from 0.9.5 official to the latest Fix W3TC on my dev environment before pushing it to my live website.

I love what I see the Fix W3TC team doing. It's excellent, high quality work that's open source/GPLed, supported by friendly and helpful people. Frankly, you all are the ones who deserve money/donations for putting in all of this incredibly high quality hard work.

All you really need is a new project name and you'll be set! Because that's the beauty of open source. You can fork it if you want and make whatever changes you desire! Just look at how [LibreOffice](https://en.wikipedia.org/wiki/LibreOffice) came to be. (It was forked from OpenOffice in 2010. They were concerned Oracle would either discontinue or restrict OpenOffice.) Now, LibreOffice is a thriving, high quality open sourced office suite!

Don't lose hope, you guys are doing something great for the community. Keep it up, let it thrive and don't get discouraged! I know I've said a lot here, and I may be speaking for many who feel the same. Keep up all the great work everyone. I hope this serves as meaningful, motivating encouragement to keep it up!

**Comment by moisb** [comment]
@Tarun80 you are full of reason in your comment. I did the upgrade to 0.9.5 in a less important website with PHP7, nginx and MariaDB in newer versions and the performance was seriously affected. I had to disable all plugins and theme and delete the official W3TC. 
@amiga-500 thank you for sharing this information. Now I am determined to change W3TC v0.9.4.1 for fix-W3TC.

**Comment by ftownes** [comment]
I'm not going to repost this in the various discussions, but if relevant folks will obviously link to it:

Some background for those who are interested: In 7y, there have been 2 folks that reached out and volunteered to contribute code, but no unsolicited code contributions. While bug reports are vital and appreciated, contributions are at the heart of open source. There have been ~5 folks (sorry if I missed someone) that have contributed translations in the past. Until recently there have been <10 submitted patches.

I believe in the community, that's why when folks like Otto and Mika reached out I immediately responded. It wasn’t a "high risk” security hole, but there were other recent security improvements that I wanted to release at once and not patch the latest version to do it since development had been ongoing since the start of the project, as many of the partners WP-CLI and others and few contributors would know.

I just wanted to share with you all that the interest in contribution is a *recent trend* and that the communication from the community to me (for the most part) has been passive and not actively engaged.

Thanks for those who have been supportive and I appreciate the interest many of you have in the project.

> Are you still considering putting it on github? Perhaps as a private invite-only repository at first before having it open to the public with the v1.0 release?

@charlesLF, my original plan was to get some folks involved and to prepare migrate the existing private github repository to public along with the relevant bits like style guide, continuous integration set up, known issues etc and get milestones etc going.

> I also think that we need to clear out a few things (such as the lack of public communication that happened over the past year or so, lack of premium support to those who paid for the plugin, identified bugs not fixed for 1+ years, etc...), before jumping into anything.

If you'd like to contribute the plugin that is fine. Customers are told that there is no support in the forums, it doesn't scale unless contributors want to organize. The folks that know me well know that I started this project because open source is a great way to impact the world. I don't expect everyone to be positive or supportive about what they perceive my actions or intentions to be, but anyone that contributes to open source for years (at any cadence) obviously must have some positive values. Unfortunately, I simply cannot address every speculation that is raised and will always fail to meet the expectations of others. For that I'm sorry.

@nigrosimone, @rabin-io, @volnus, @FPCSJames I caught up with @szepeviktor on a call earlier this week. Are you all in the Slack Team channel by any chance?

**Comment by jkirker** [comment]
What @Tarun80 says makes a lot of sense.  At the same time I'm excited to see what W3TC 1.0 has to offer.  @ftownes do you have an anticipated timeline or launch date for this?

Some of the sites which I updated to resolve the XSS issue retained their settings while others did not.  All of these sites are on mirrored configs/environments as I own the hosting company they reside on.  They were not all installed at the same time though - and all have their unique blend of plugins.  I'm not sure what happened nor do I have time to diagnose the issues.

At this point I like the idea of continuing the fork and getting it into the repository so that updates are more easily managed by the users.  Otherwise, management outside of the WP environment without yet another plugin can become a real challenge when someone is responsible for a plethora of properties.

With that said, there's no reason why both plugins couldn't benefit from one another ongoing - migrating code in when the one adds something which the other perceives as valuable to its users.

As @Tarun80 and others have said throughout history, "Competition leads to innovation."

Just my 2 cents.

May the best and "most supported plugin" win...

PS. @ftownes - this is in no way a dig on you...  You've typically been there in the forums when needed.  And with the massive install base that you have, without taking in $$ for support there is really no way to do it without a huge involvement from the community.  With so many poorly written plugins out there that can kludge things, it's a real nightmare.  I think we all know this.  Unfortunately none of us can live and work completely for free. ;)

**Comment by szepeviktor** [comment]
> May the best and "most supported plugin" win...

I think the real winner is who can sustain himself on a free plugin.

**Comment by FPCSJames** [comment]
@ftownes I'm not in the Slack channel - quite frankly I'm not even sure which one that would be!

**Comment by nigrosimone** [comment]
> Are you all in the Slack Team channel by any chance?

@ftownes ihave created a slack team for "fix-w3tc" team here: https://fix-w3tc.slack.com

@szepeviktor just invited. Now i need a @charlesLF e-mail, @amiga-500 e-mail, @Volnus e-mail (hey guys i don't have yours email!)

every [contributors](https://github.com/szepeviktor/fix-w3tc/graphs/contributors) can send me a mail for invitation in slack at nigro.simone@gmail.com

**Comment by Volnus** [comment]
@nigrosimone email has been sent

**Comment by szepeviktor** [comment]
I hope all of the following questions will fit into this Slack team.
