### ISSUE TITLE
files appear to be missing or out of place. Please re-install plugin or remove wp-content/advanced-cache.php

### ISSUE THREAD

**Issue by kevin25** [szepeviktor/fix-w3tc#88]
I got this always. I tried to remove the plugin, remove that file and re-install again. But till got the same issue.

**Comment by nigrosimone** [comment]
you talking about fix-w3tc (community github version) or w3 total cache (official wp.org version)?

side note: check if /wp-content/ directory has advanced-cache.php file in place.

**Comment by kevin25** [comment]
It's fix-w3tc. The advanced-cache.php is in place.

**Comment by nigrosimone** [comment]
you have in `wp-config.php`:
```php
    define('WP_CACHE', true);
```

**Comment by kevin25** [comment]
Yes, of course

**Comment by amiga-500** [comment]
Hi @kevin25...not sure if you've moved on and using (successfully) the official 0.9.5 found on WP.org or if you are still dealing with this problem.  Love to know.

**Comment by amiga-500** [comment]
@kevin25 the problem seems to be that you did not rename the fix-w3tc directory to **w3-total-cache**.  _advanced-cache.php_ hardcodes the need for a directory with that name.

I am going to mark this as closed since all indications seem to point to this.  And i figure you've moved on days ago.

Kimberly.
